// src/config/modelConfigs.js



// LevelE-101    ELX-1101
// LevelE-102    ELX-1102
// LevelE-103    ELX-1103
// LevelE-104    ELX-1104
// LevelE-105    ELX-1105
// LevelE-106    ELX-1106
// LevelE-107    ELX-1107
// LevelE-108    ELX-1108
// LevelR-201    RLX-2201
// LevelR-202    RLX-2202
// LevelR-203    RLX-2203
// LevelR-204    RLX-2204
// LevelR-205    RLX-2205
// LevelC-301    CLX-3301
// LevelC-302    CLX-3302

export const modelConfigs = {
  // ────────────────────────────────────────────────
  //                LEVELe-101  (your current one)
  // ────────────────────────────────────────────────
  "ELX-1101": {
    name: "ELX-1101",
    skeletonViews: {
      1: [
        { id: 1, img: "/C SK/1 GAF/V1/1.png" },
        { id: 2, img: "/C SK/1 GAF/V1/2.png" },
        { id: 3, img: "/C SK/1 GAF/V1/3.png" },
        { id: 4, img: "/C SK/1 GAF/V1/4.png" },
        { id: 5, img: "/C SK/1 GAF/V1/5.png" },
        { id: 6, img: "/C SK/1 GAF/V1/6.png" },
        { id: 7, img: "/C SK/1 GAF/V1/7.png" },
        { id: 8, img: "/C SK/1 GAF/V1/8.png" },
        { id: 9, img: "/C SK/1 GAF/V1/9.png" },
        { id: 10, img: "/C SK/1 GAF/V1/10.png" },
        { id: 11, img: "/C SK/1 GAF/V1/11.png" },
        { id: 12, img: "/C SK/1 GAF/V1/12.png" },
        { id: 13, img: "/C SK/1 GAF/V1/13.png" },
        { id: 14, img: "/C SK/1 GAF/V1/14.png" },
        { id: 15, img: "/C SK/1 GAF/V1/15.png" },
      ],
      2: [
        { id: 1, img: "/C SK/1 GAF/V2/1.png" },
        { id: 2, img: "/C SK/1 GAF/V2/2.png" },
        { id: 3, img: "/C SK/1 GAF/V2/3.png" },
        { id: 4, img: "/C SK/1 GAF/V2/4.png" },
        { id: 5, img: "/C SK/1 GAF/V2/5.png" },
        { id: 6, img: "/C SK/1 GAF/V2/6.png" },
        { id: 7, img: "/C SK/1 GAF/V2/7.png" },
        { id: 8, img: "/C SK/1 GAF/V2/8.png" },
        { id: 9, img: "/C SK/1 GAF/V2/9.png" },
        { id: 10, img: "/C SK/1 GAF/V2/10.png" },
        { id: 11, img: "/C SK/1 GAF/V2/11.png" },
        { id: 12, img: "/C SK/1 GAF/V2/12.png" },
        { id: 13, img: "/C SK/1 GAF/V2/13.png" },
        { id: 14, img: "/C SK/1 GAF/V2/14.png" },
        { id: 15, img: "/C SK/1 GAF/V2/15.png" },
        { id: 16, img: "/C SK/1 GAF/V2/16.png" },
        { id: 17, img: "/C SK/1 GAF/V2/17.png" },
        { id: 18, img: "/C SK/1 GAF/V2/18.png" },
        { id: 19, img: "/C SK/1 GAF/V2/19.png" },
        { id: 20, img: "/C SK/1 GAF/V2/20.png" },
      ],
      3: [
        { id: 1, img: "/C SK/1 GAF/V3/1.png" },
        { id: 2, img: "/C SK/1 GAF/V3/2.png" },
        { id: 3, img: "/C SK/1 GAF/V3/3.png" },
        { id: 4, img: "/C SK/1 GAF/V3/4.png" },
        { id: 5, img: "/C SK/1 GAF/V3/5.png" },
        { id: 6, img: "/C SK/1 GAF/V3/6.png" },
        { id: 7, img: "/C SK/1 GAF/V3/7.png" },
        { id: 8, img: "/C SK/1 GAF/V3/8.png" },
        { id: 9, img: "/C SK/1 GAF/V3/9.png" },
        { id: 10, img: "/C SK/1 GAF/V3/10.png" },
        { id: 11, img: "/C SK/1 GAF/V3/11.png" },
      ],
    },
    layerToPanelByView: {
      1: {
        1: { zone: "A", panelNum: 1 },
        2: { zone: "A", panelNum: 2 },
        3: { zone: "A", panelNum: 3 },
        4: { zone: "A", panelNum: 4 },
        5: { zone: "B", panelNum: 1 },
        6: { zone: "B", panelNum: 2 },
        7: { zone: "C", panelNum: 1 },
        8: { zone: "C", panelNum: 2 },
        9: { zone: "D", panelNum: 1 },
        10: { zone: "D", panelNum: 2 },
        11: { zone: "E", panelNum: 1 },
        12: { zone: "E", panelNum: 2 },
        13: { zone: "F", panelNum: 1 },
        // ... your current mapping
      },
      2: {
        1: { zone: "A", panelNum: 1 },
        2: { zone: "A", panelNum: 2 },
        3: { zone: "A", panelNum: 3 },
        4: { zone: "A", panelNum: 3 },
        5: { zone: "A", panelNum: 4 },
        6: { zone: "A", panelNum: 4 },
        7: { zone: "B", panelNum: 1 },
        8: { zone: "C", panelNum: 1 },
        9: { zone: "D", panelNum: 1 },
        10: { zone: "B", panelNum: 2 },
        11: { zone: "B", panelNum: 2 },
        12: { zone: "C", panelNum: 2 },
        13: { zone: "C", panelNum: 2 },
        14: { zone: "D", panelNum: 2 },
        15: { zone: "D", panelNum: 2 },
        16: { zone: "E", panelNum: 1 },
        17: { zone: "E", panelNum: 2 },
        18: { zone: "F", panelNum: 1 },
      },
      3: {
        1: { zone: "A", panelNum: 3 },
        2: { zone: "A", panelNum: 4 },
        3: { zone: "B", panelNum: 2 },
        4: { zone: "C", panelNum: 2 },
        5: { zone: "D", panelNum: 2 },
        6: { zone: "E", panelNum: 1 },
        7: { zone: "E", panelNum: 2 },
        8: { zone: "F", panelNum: 1 },
        9: { zone: "F", panelNum: 2 },
      },
    },
    // ── LEVELe-101 ──
    // Zones: A(4), B(2), C(2), D(2), E(2), F(1)
    // V1: A1→L1, A2→L2, A3→L3, A4→L4, B1→L5, B2→L6, C1→L7, C2→L8, D1→L9, D2→L10, E1→L11, E2→L12, F1→L13
    panelMap: {
      A: [
        { layerId: 1, panelNum: 1, top: "50%", left: "19%" },
        { layerId: 2, panelNum: 2, top: "50%", left: "56%" },
        { layerId: 3, panelNum: 3, top: "50%", left: "64%" },
        { layerId: 4, panelNum: 4, top: "50%", left: "85%" },
      ],
      B: [
        { layerId: 5, panelNum: 1, top: "30%", left: "38%" },
        { layerId: 6, panelNum: 2, top: "30%", left: "72%" },
      ],
      C: [
        { layerId: 7, panelNum: 1, top: "50%", left: "38%" },
        { layerId: 8, panelNum: 2, top: "50%", left: "72%" },
      ],
      D: [
        { layerId: 9, panelNum: 1, top: "70%", left: "38%" },
        { layerId: 10, panelNum: 2, top: "70%", left: "72%" },
      ],
      E: [
        { layerId: 13, panelNum: 1, top: "24%", left: "60%" },
        { layerId: 14, panelNum: 2, top: "77%", left: "60%" },
      ],
      F: [
        { layerId: 11, panelNum: 1, top: "24%", left: "60%" },
        { layerId: 12, panelNum: 2, top: "77%", left: "60%" },
      ],
    },
  },

  // ────────────────────────────────────────────────
  //                LEVELe-102
  // ────────────────────────────────────────────────
  "ELX-1102": {
    name: "ELX-1102",
    skeletonViews: {
      1: [
        { id: 1, img: "/C SK/2 GAF/V1/1.png" },
        { id: 2, img: "/C SK/2 GAF/V1/2.png" },
        { id: 3, img: "/C SK/2 GAF/V1/3.png" },
        { id: 4, img: "/C SK/2 GAF/V1/4.png" },
        { id: 5, img: "/C SK/2 GAF/V1/5.png" },
        { id: 6, img: "/C SK/2 GAF/V1/6.png" },
        { id: 7, img: "/C SK/2 GAF/V1/7.png" },
        { id: 8, img: "/C SK/2 GAF/V1/8.png" },
        { id: 9, img: "/C SK/2 GAF/V1/9.png" },
        { id: 10, img: "/C SK/2 GAF/V1/10.png" },
        { id: 11, img: "/C SK/2 GAF/V1/11.png" },
      ],
      2: [
        { id: 1, img: "/C SK/2 GAF/V2/1.png" },
        { id: 2, img: "/C SK/2 GAF/V2/2.png" },
        { id: 3, img: "/C SK/2 GAF/V2/3.png" },
        { id: 4, img: "/C SK/2 GAF/V2/4.png" },
        { id: 5, img: "/C SK/2 GAF/V2/5.png" },
        { id: 6, img: "/C SK/2 GAF/V2/6.png" },
        { id: 7, img: "/C SK/2 GAF/V2/7.png" },
        { id: 8, img: "/C SK/2 GAF/V2/8.png" },
        { id: 9, img: "/C SK/2 GAF/V2/9.png" },
        { id: 10, img: "/C SK/2 GAF/V2/10.png" },
        { id: 11, img: "/C SK/2 GAF/V2/11.png" },
        { id: 12, img: "/C SK/2 GAF/V2/12.png" },
        { id: 13, img: "/C SK/2 GAF/V2/13.png" },
        { id: 14, img: "/C SK/2 GAF/V2/14.png" },
      ],
      3: [
        { id: 1, img: "/C SK/2 GAF/V3/1.png" },
        { id: 2, img: "/C SK/2 GAF/V3/2.png" },
        { id: 3, img: "/C SK/2 GAF/V3/3.png" },
        { id: 4, img: "/C SK/2 GAF/V3/4.png" },
        { id: 5, img: "/C SK/2 GAF/V3/5.png" },
        { id: 6, img: "/C SK/2 GAF/V3/6.png" },
        { id: 7, img: "/C SK/2 GAF/V3/7.png" },
        { id: 8, img: "/C SK/2 GAF/V3/8.png" },
        { id: 9, img: "/C SK/2 GAF/V3/9.png" },
      ],
    },
    // here we change the panel
    layerToPanelByView: {
      1: {
        1: { zone: "A", panelNum: 1 },
        2: { zone: "A", panelNum: 2 },
        3: { zone: "B", panelNum: 1 },
        4: { zone: "B", panelNum: 2 },
        5: { zone: "C", panelNum: 1 },
        6: { zone: "C", panelNum: 2 },
        7: { zone: "D", panelNum: 1 },
        8: { zone: "D", panelNum: 2 },
        9: { zone: "E", panelNum: 1 },
      },
      2: {
        1: { zone: "A", panelNum: 1 },
        2: { zone: "A", panelNum: 2 },
        3: { zone: "A", panelNum: 2 },
        4: { zone: "B", panelNum: 1 },
        5: { zone: "B", panelNum: 2 },
        6: { zone: "B", panelNum: 2 },
        7: { zone: "C", panelNum: 1 },
        8: { zone: "C", panelNum: 2 },
        9: { zone: "C", panelNum: 2 },
        10: { zone: "D", panelNum: 1 },
        11: { zone: "D", panelNum: 2 },
        12: { zone: "E", panelNum: 1 },
      },
      3: {
        1: { zone: "A", panelNum: 2 },
        2: { zone: "B", panelNum: 2 },
        3: { zone: "C", panelNum: 2 },
        4: { zone: "D", panelNum: 1 },
        5: { zone: "D", panelNum: 2 },
        6: { zone: "E", panelNum: 1 },
        7: { zone: "E", panelNum: 1 },
      },
    },
    // ── LEVELe-102 ──
    // Zones: A(2), B(2), C(2), D(2), E(1)
    // V1: A1→L1, A2→L2, B1→L3, B2→L4, C1→L5, C2→L6, D1→L7, D2→L8, E1→L9
    panelMap: {
      A: [
        { layerId: 1, panelNum: 1, top: "30%", left: "25%" },
        { layerId: 2, panelNum: 2, top: "30%", left: "75%" },
      ],
      B: [
        { layerId: 3, panelNum: 1, top: "50%", left: "25%" },
        { layerId: 4, panelNum: 2, top: "50%", left: "75%" },
      ],
      C: [
        { layerId: 5, panelNum: 1, top: "70%", left: "25%" },
        { layerId: 6, panelNum: 2, top: "70%", left: "75%" },
      ],
      D: [
        { layerId: 7, panelNum: 1, top: "25%", left: "61%" },
        { layerId: 8, panelNum: 2, top: "77%", left: "61%" },
      ],
      E: [{ layerId: 9, panelNum: 1, top: "50%", left: "50%" }],
    },
  },
  // ────────────────────────────────────────────────
  //                LEVELe-103
  // ────────────────────────────────────────────────
  "ELX-1103": {
    name: "ELX-1103",
    skeletonViews: {
      1: [
        { id: 1, img: "/C SK/3 GAF/V1/1.png" },
        { id: 2, img: "/C SK/3 GAF/V1/2.png" },
        { id: 3, img: "/C SK/3 GAF/V1/3.png" },
        { id: 4, img: "/C SK/3 GAF/V1/4.png" },
        { id: 5, img: "/C SK/3 GAF/V1/5.png" },
        { id: 6, img: "/C SK/3 GAF/V1/6.png" },
        { id: 7, img: "/C SK/3 GAF/V1/7.png" },
        { id: 8, img: "/C SK/3 GAF/V1/8.png" },
        { id: 9, img: "/C SK/3 GAF/V1/9.png" },
        { id: 10, img: "/C SK/3 GAF/V1/10.png" },
      ],
      2: [
        { id: 1, img: "/C SK/3 GAF/V2/1.png" },
        { id: 2, img: "/C SK/3 GAF/V2/2.png" },
        { id: 3, img: "/C SK/3 GAF/V2/3.png" },
        { id: 4, img: "/C SK/3 GAF/V2/4.png" },
        { id: 5, img: "/C SK/3 GAF/V2/5.png" },
        { id: 6, img: "/C SK/3 GAF/V2/6.png" },
        { id: 7, img: "/C SK/3 GAF/V2/7.png" },
        { id: 8, img: "/C SK/3 GAF/V2/8.png" },
        { id: 9, img: "/C SK/3 GAF/V2/9.png" },
        { id: 10, img: "/C SK/3 GAF/V2/10.png" },
        { id: 11, img: "/C SK/3 GAF/V2/11.png" },
        { id: 12, img: "/C SK/3 GAF/V2/12.png" },
      ],
      3: [
        { id: 1, img: "/C SK/3 GAF/V3/1.png" },
        { id: 2, img: "/C SK/3 GAF/V3/2.png" },
        { id: 3, img: "/C SK/3 GAF/V3/3.png" },
        { id: 4, img: "/C SK/3 GAF/V3/4.png" },
        { id: 5, img: "/C SK/3 GAF/V3/5.png" },
        { id: 6, img: "/C SK/3 GAF/V3/6.png" },
        { id: 7, img: "/C SK/3 GAF/V3/7.png" },
        { id: 8, img: "/C SK/3 GAF/V3/8.png" },
      ],
    },
    layerToPanelByView: {
      1: {
        1: { zone: "A", panelNum: 1 },
        2: { zone: "A", panelNum: 2 },
        3: { zone: "B", panelNum: 1 },
        4: { zone: "B", panelNum: 2 },
        5: { zone: "C", panelNum: 1 },
        6: { zone: "D", panelNum: 1 },
        7: { zone: "D", panelNum: 2 },
        8: { zone: "E", panelNum: 1 },
        // ... your current mapping
      },
      2: {
        1: { zone: "A", panelNum: 1 },
        2: { zone: "A", panelNum: 2 },
        3: { zone: "A", panelNum: 2 },
        4: { zone: "B", panelNum: 1 },
        5: { zone: "B", panelNum: 2 },
        6: { zone: "B", panelNum: 2 },
        7: { zone: "C", panelNum: 1 },
        8: { zone: "D", panelNum: 1 },
        9: { zone: "D", panelNum: 2 },
        10: { zone: "E", panelNum: 2 },
      },
      3: {
        1: { zone: "A", panelNum: 2 },
        2: { zone: "B", panelNum: 2 },
        3: { zone: "D", panelNum: 1 },
        4: { zone: "D", panelNum: 2 },
        5: { zone: "E", panelNum: 1 },
        6: { zone: "E", panelNum: 2 },
      },
    },

    // ── LEVELe-103 ──
    // Zones: A(2), B(2), C(1), D(2), E(2)
    // V1: A1→L1, A2→L2, B1→L3, B2→L4, C1→L5, D1→L6, D2→L7, E1→L8
    // V2 introduces E2 (layer 10)
    panelMap: {
      A: [
        { layerId: 1, panelNum: 1, top: "50%", left: "18%" },
        { layerId: 2, panelNum: 2, top: "50%", left: "68%" },
      ],
      B: [
        { layerId: 3, panelNum: 1, top: "33%", left: "29%" },
        { layerId: 4, panelNum: 2, top: "33%", left: "82%" },
      ],
      C: [{ layerId: 5, panelNum: 1, top: "50%", left: "50%" }],
      D: [
        { layerId: 6, panelNum: 1, top: "25%", left: "61%" },
        { layerId: 7, panelNum: 2, top: "77%", left: "61%" },
      ],
      E: [
        { layerId: 8, panelNum: 1, top: "25%", left: "61%" },
        { layerId: 10, panelNum: 2, top: "77%", left: "61%" },
      ],
    },
  },
  // ────────────────────────────────────────────────
  //                ELX-1104
  // ────────────────────────────────────────────────
  "ELX-1104": {
    name: "ELX-1104",
    skeletonViews: {
      1: [
        { id: 1, img: "/C SK/4 GAF/V1/1.png" },
        { id: 2, img: "/C SK/4 GAF/V1/2.png" },
        { id: 3, img: "/C SK/4 GAF/V1/3.png" },
        { id: 4, img: "/C SK/4 GAF/V1/4.png" },
        { id: 5, img: "/C SK/4 GAF/V1/5.png" },
        { id: 6, img: "/C SK/4 GAF/V1/6.png" },
        { id: 7, img: "/C SK/4 GAF/V1/7.png" },
        { id: 8, img: "/C SK/4 GAF/V1/8.png" },
        { id: 9, img: "/C SK/4 GAF/V1/9.png" },
        { id: 10, img: "/C SK/4 GAF/V1/10.png" },
      ],
      2: [
        { id: 1, img: "/C SK/4 GAF/V2/1.png" },
        { id: 2, img: "/C SK/4 GAF/V2/2.png" },
        { id: 3, img: "/C SK/4 GAF/V2/3.png" },
        { id: 4, img: "/C SK/4 GAF/V2/4.png" },
        { id: 5, img: "/C SK/4 GAF/V2/5.png" },
        { id: 6, img: "/C SK/4 GAF/V2/6.png" },
        { id: 7, img: "/C SK/4 GAF/V2/7.png" },
        { id: 8, img: "/C SK/4 GAF/V2/8.png" },
        { id: 9, img: "/C SK/4 GAF/V2/9.png" },
        { id: 10, img: "/C SK/4 GAF/V2/10.png" },
        { id: 11, img: "/C SK/4 GAF/V2/11.png" },
        { id: 12, img: "/C SK/4 GAF/V2/12.png" },
      ],
      3: [
        { id: 1, img: "/C SK/4 GAF/V3/1.png" },
        { id: 2, img: "/C SK/4 GAF/V3/2.png" },
        { id: 3, img: "/C SK/4 GAF/V3/3.png" },
        { id: 4, img: "/C SK/4 GAF/V3/4.png" },
        { id: 5, img: "/C SK/4 GAF/V3/5.png" },
        { id: 6, img: "/C SK/4 GAF/V3/6.png" },
        { id: 7, img: "/C SK/4 GAF/V3/7.png" },
        { id: 8, img: "/C SK/4 GAF/V3/8.png" },
      ],
    },

    layerToPanelByView: {
      1: {
        1: { zone: "A", panelNum: 1 },
        2: { zone: "A", panelNum: 2 },
        3: { zone: "B", panelNum: 1 },
        4: { zone: "B", panelNum: 2 },
        5: { zone: "C", panelNum: 1 },
        6: { zone: "D", panelNum: 1 },
        7: { zone: "D", panelNum: 2 },
        8: { zone: "E", panelNum: 1 },
        // ... your current mapping
      },
      2: {
        1: { zone: "A", panelNum: 1 },
        2: { zone: "A", panelNum: 2 },
        3: { zone: "A", panelNum: 2 },
        4: { zone: "B", panelNum: 1 },
        5: { zone: "B", panelNum: 2 },
        6: { zone: "B", panelNum: 2 },
        7: { zone: "C", panelNum: 1 },
        8: { zone: "D", panelNum: 1 },
        9: { zone: "D", panelNum: 2 },
        10: { zone: "E", panelNum: 1 },
      },
      3: {
        1: { zone: "A", panelNum: 2 },
        2: { zone: "B", panelNum: 2 },
        3: { zone: "D", panelNum: 1 },
        4: { zone: "D", panelNum: 2 },
        5: { zone: "E", panelNum: 1 },
        6: { zone: "E", panelNum: 2 },
      },
    },

    // ── LEVELe-104 ──
    // Zones: A(2), B(2), C(1), D(2), E(2)
    // V1: A1→L1, A2→L2, B1→L3, B2→L4, C1→L5, D1→L6, D2→L7, E1→L8
    // V3 introduces E2 (layer 6 reused — keep as-is from layerToPanelByView)
    panelMap: {
      A: [
        { layerId: 1, panelNum: 1, top: "50%", left: "18%" },
        { layerId: 2, panelNum: 2, top: "50%", left: "68%" },
      ],
      B: [
        { layerId: 3, panelNum: 1, top: "43%", left: "57%" },
        { layerId: 4, panelNum: 2, top: "43%", left: "82%" },
      ],
      C: [{ layerId: 5, panelNum: 1, top: "50%", left: "40%" }],

      D: [
        { layerId: 8, panelNum: 1, top: "24%", left: "61%" },
        { layerId: 9, panelNum: 2, top: "77%", left: "61%" },
      ],
      E: [
        { layerId: 6, panelNum: 1, top: "24%", left: "61%" },
        { layerId: 7, panelNum: 2, top: "77%", left: "61%" },
      ],
    },
  },
  // ────────────────────────────────────────────────
  //                ELX-1105
  // ────────────────────────────────────────────────
  "ELX-1105": {
    name: "ELX-1105",
    skeletonViews: {
      1: [
        { id: 1, img: "/C SK/5 GAF/V1/1.png" },
        { id: 2, img: "/C SK/5 GAF/V1/2.png" },
        { id: 3, img: "/C SK/5 GAF/V1/3.png" },
        { id: 4, img: "/C SK/5 GAF/V1/4.png" },
        { id: 5, img: "/C SK/5 GAF/V1/5.png" },
        { id: 6, img: "/C SK/5 GAF/V1/6.png" },
        { id: 7, img: "/C SK/5 GAF/V1/7.png" },
        { id: 8, img: "/C SK/5 GAF/V1/8.png" },
        { id: 9, img: "/C SK/5 GAF/V1/9.png" },
        { id: 10, img: "/C SK/5 GAF/V1/10.png" },
        { id: 11, img: "/C SK/5 GAF/V1/11.png" },
      ],
      2: [
        { id: 1, img: "/C SK/5 GAF/V2/1.png" },
        { id: 2, img: "/C SK/5 GAF/V2/2.png" },
        { id: 3, img: "/C SK/5 GAF/V2/3.png" },
        { id: 4, img: "/C SK/5 GAF/V2/4.png" },
        { id: 5, img: "/C SK/5 GAF/V2/5.png" },
        { id: 6, img: "/C SK/5 GAF/V2/6.png" },
        { id: 7, img: "/C SK/5 GAF/V2/7.png" },
        { id: 8, img: "/C SK/5 GAF/V2/8.png" },
        { id: 9, img: "/C SK/5 GAF/V2/9.png" },
        { id: 10, img: "/C SK/5 GAF/V2/10.png" },
        { id: 11, img: "/C SK/5 GAF/V2/11.png" },
        { id: 12, img: "/C SK/5 GAF/V2/12.png" },
        { id: 13, img: "/C SK/5 GAF/V2/13.png" },
      ],
      3: [
        { id: 1, img: "/C SK/5 GAF/V3/1.png" },
        { id: 2, img: "/C SK/5 GAF/V3/2.png" },
        { id: 3, img: "/C SK/5 GAF/V3/3.png" },
        { id: 4, img: "/C SK/5 GAF/V3/4.png" },
        { id: 5, img: "/C SK/5 GAF/V3/5.png" },
        { id: 6, img: "/C SK/5 GAF/V3/6.png" },
        { id: 7, img: "/C SK/5 GAF/V3/7.png" },
        { id: 8, img: "/C SK/5 GAF/V3/8.png" },
      ],
    },

    layerToPanelByView: {
      1: {
        1: { zone: "A", panelNum: 1 },
        2: { zone: "A", panelNum: 2 },
        3: { zone: "B", panelNum: 1 },
        4: { zone: "B", panelNum: 2 },
        5: { zone: "C", panelNum: 1 },
        6: { zone: "C", panelNum: 2 },
        7: { zone: "D", panelNum: 1 },
        8: { zone: "D", panelNum: 2 },
        9: { zone: "E", panelNum: 1 },

        // ... your current mapping
      },
      2: {
        1: { zone: "A", panelNum: 1 },
        2: { zone: "A", panelNum: 2 },
        3:{zone:"B", panelNum:1},
        4:{zone:"B", panelNum:2},
        5:{zone:"C", panelNum:1},
        6:{zone:"C", panelNum:1},
        7:{zone:"C", panelNum:2},
        8:{zone:"C", panelNum:2},
        9:{zone:"D", panelNum:1},
        10:{zone:"D", panelNum:2},
        11:{zone:"E",panelNum:1},
      },
      3: {
        1: { zone: "C", panelNum: 1 },
        2: { zone: "C", panelNum: 2 },
        3: { zone: "D", panelNum: 1 },
        4: { zone: "D", panelNum: 2 },
        5: { zone: "E", panelNum: 1 },
     
      },
    },
    // ── LEVELe-105 ──
    // Zones: A(2), B(2), C(1), D(2), E(2)
    // V1: A1→L1, A2→L2, B1→L3, B2→L4, C1→L5, D1→L6, D2→L7, E1→L8
    // V3 introduces E2 (layer 6 reused — keep as-is from layerToPanelByView)
    panelMap: {
      A: [
        { layerId: 1, panelNum: 1, top: "40%", left: "18%" },
        { layerId: 2, panelNum: 2, top: "40%", left: "57%" },
      ],
      B: [
        { layerId: 3, panelNum: 1, top: "50%", left: "40%" },
        { layerId: 4, panelNum: 2, top: "73%", left: "40%" },
      ],
      C: [
        { layerId: 5, panelNum: 1, top: "50%", left: "67%" },
        { layerId: 6, panelNum: 2, top: "50%", left: "82%" },

      ],

      D: [
        { layerId: 9, panelNum: 1, top: "24%", left: "61%" },
        { layerId: 10, panelNum: 2, top: "77%", left: "61%" },
      ],
      E: [
        { layerId: 7, panelNum: 1, top: "24%", left: "61%" },
        { layerId: 8, panelNum: 2, top: "77%", left: "61%" },
      ],
    },
  },
  
  
  // ────────────────────────────────────────────────
  //                ELX-1106
  // ────────────────────────────────────────────────
  "ELX-1106": {
    name: "ELX-1106",
    skeletonViews: {
      1: [
        { id: 1, img: "/C SK/6 GAF/V1/1.png" },
        { id: 2, img: "/C SK/6 GAF/V1/2.png" },
        { id: 3, img: "/C SK/6 GAF/V1/3.png" },
        { id: 4, img: "/C SK/6 GAF/V1/4.png" },
        { id: 5, img: "/C SK/6 GAF/V1/5.png" },
        { id: 6, img: "/C SK/6 GAF/V1/6.png" },
        { id: 7, img: "/C SK/6 GAF/V1/7.png" },
        { id: 8, img: "/C SK/6 GAF/V1/8.png" },
        { id: 9, img: "/C SK/6 GAF/V1/9.png" },
        { id: 10, img: "/C SK/6 GAF/V1/10.png" },
        { id: 11, img: "/C SK/6 GAF/V1/11.png" },
        { id: 12, img: "/C SK/6 GAF/V1/12.png" },
        { id: 13, img: "/C SK/6 GAF/V1/13.png" },
        { id: 14, img: "/C SK/6 GAF/V1/14.png" },
      ],
      2: [
        { id: 1, img: "/C SK/6 GAF/V2/1.png" },
        { id: 2, img: "/C SK/6 GAF/V2/2.png" },
        { id: 3, img: "/C SK/6 GAF/V2/3.png" },
        { id: 4, img: "/C SK/6 GAF/V2/4.png" },
        { id: 5, img: "/C SK/6 GAF/V2/5.png" },
        { id: 6, img: "/C SK/6 GAF/V2/6.png" },
        { id: 7, img: "/C SK/6 GAF/V2/7.png" },
        { id: 8, img: "/C SK/6 GAF/V2/8.png" },
        { id: 9, img: "/C SK/6 GAF/V2/9.png" },
        { id: 10, img: "/C SK/6 GAF/V2/10.png" },
        { id: 11, img: "/C SK/6 GAF/V2/11.png" },
        { id: 12, img: "/C SK/6 GAF/V2/12.png" },
        { id: 13, img: "/C SK/6 GAF/V2/13.png" },
        { id: 14, img: "/C SK/6 GAF/V2/14.png" },
        { id: 15, img: "/C SK/6 GAF/V2/15.png" },
        { id: 16, img: "/C SK/6 GAF/V2/16.png" },
        { id: 17, img: "/C SK/6 GAF/V2/17.png" },
        { id: 18, img: "/C SK/6 GAF/V2/18.png" },
      ],
      3: [
        { id: 1, img: "/C SK/6 GAF/V3/1.png" },
        { id: 2, img: "/C SK/6 GAF/V3/2.png" },
        { id: 3, img: "/C SK/6 GAF/V3/3.png" },
        { id: 4, img: "/C SK/6 GAF/V3/4.png" },
        { id: 5, img: "/C SK/6 GAF/V3/5.png" },
        { id: 6, img: "/C SK/6 GAF/V3/6.png" },
        { id: 7, img: "/C SK/6 GAF/V3/7.png" },
        { id: 8, img: "/C SK/6 GAF/V3/8.png" },
        { id: 9, img: "/C SK/6 GAF/V3/9.png" },
        { id: 10, img: "/C SK/6 GAF/V3/10.png" },
      ],
    },

    layerToPanelByView: {
      1: {
        1: { zone: "A", panelNum: 1 },
        2: { zone: "A", panelNum: 2 },
        3: { zone: "A", panelNum: 3 },
        4: { zone: "A", panelNum: 4 },
        5: { zone: "B", panelNum: 1 },
        6: { zone: "B", panelNum: 2 },
        7: { zone: "B", panelNum: 3 },
        8: { zone: "B", panelNum: 4 },
        9: { zone: "C", panelNum: 1 },
        10: { zone: "D", panelNum: 1 },
        11: { zone: "D", panelNum: 2 },
        12: { zone: "E", panelNum: 1 },

        // ... your current mapping
      },
      2: {
        1: { zone: "A", panelNum: 1 },
        2: { zone: "A", panelNum: 2 },
        3: { zone: "A", panelNum: 3 },
        4: { zone: "A", panelNum: 3 },
        5: { zone: "A", panelNum: 4 },
        6: { zone: "A", panelNum: 4 },
        7: { zone: "B", panelNum: 1 },
        8: { zone: "B", panelNum: 2 },
        9: { zone: "B", panelNum: 3 },
        10: { zone: "B", panelNum: 3 },
        11: { zone: "B", panelNum: 4 },
        12: { zone: "B", panelNum: 4 },
        13: { zone: "C", panelNum: 1 },
        14: { zone: "D", panelNum: 1 },
        15: { zone: "D", panelNum: 2 },
        16: { zone: "E", panelNum: 1 },
      },
      3: {
        1: { zone: "A", panelNum: 3 },
        2: { zone: "A", panelNum: 4 },
        3: { zone: "B", panelNum: 3 },
        4: { zone: "B", panelNum: 4 },
        5: { zone: "D", panelNum: 1 },
        6: { zone: "D", panelNum: 2 },
        7: { zone: "E", panelNum: 1 },
        8: { zone: "E", panelNum: 2 },
      },
    },
    // ── LEVELe-106 ──
    // Zones: A(4), B(4), C(1), D(2), E(1)
    // V1: A1→L1, A2→L2, A3→L3, A4→L4, B1→L5, B2→L6, B3→L7, B4→L8, C1→L9, D1→L10, D2→L11, E1→L12
    panelMap: {
      A: [
        { layerId: 1, panelNum: 1, top: "35%", left: "18%" },
        { layerId: 2, panelNum: 2, top: "35%", left: "56%" },
        { layerId: 3, panelNum: 3, top: "35%", left: "67%" },
        { layerId: 4, panelNum: 4, top: "35%", left: "82%" },
      ],
      B: [
        { layerId: 5, panelNum: 1, top: "70%", left: "18%" },
        { layerId: 6, panelNum: 2, top: "70%", left: "56%" },
        { layerId: 7, panelNum: 3, top: "70%", left: "67%" },
        { layerId: 8, panelNum: 4, top: "70%", left: "82%" },
      ],
      C: [{ layerId: 9, panelNum: 1, top: "50%", left: "40%" }],
      D: [
        { layerId: 12, panelNum: 1, top: "25%", left: "61%" },
        { layerId: 13, panelNum: 2, top: "77%", left: "61%" },
      ],
      E: [
        { layerId: 10, panelNum: 1, top: "25%", left: "61%" },
        { layerId: 11, panelNum: 2, top: "77%", left: "61%" },

      ],
    },
  },
  // ────────────────────────────────────────────────
  //                ELX-1107
  // ────────────────────────────────────────────────
  "ELX-1107": {
    name: "ELX-1107",
    skeletonViews: {
      1: [
        { id: 1, img: "/C SK/7 GAF/V1/1.png" },
        { id: 2, img: "/C SK/7 GAF/V1/2.png" },
        { id: 3, img: "/C SK/7 GAF/V1/3.png" },
        { id: 4, img: "/C SK/7 GAF/V1/4.png" },
        { id: 5, img: "/C SK/7 GAF/V1/5.png" },
        { id: 6, img: "/C SK/7 GAF/V1/6.png" },
        { id: 7, img: "/C SK/7 GAF/V1/7.png" },
        { id: 8, img: "/C SK/7 GAF/V1/8.png" },
        { id: 9, img: "/C SK/7 GAF/V1/9.png" },
        { id: 10, img: "/C SK/7 GAF/V1/10.png" },
        { id: 11, img: "/C SK/7 GAF/V1/11.png" },
        { id: 12, img: "/C SK/7 GAF/V1/12.png" },
        { id: 13, img: "/C SK/7 GAF/V1/13.png" },
        { id: 14, img: "/C SK/7 GAF/V1/14.png" },
        { id: 15, img: "/C SK/7 GAF/V1/15.png" },
        { id: 16, img: "/C SK/7 GAF/V1/16.png" },
        { id: 17, img: "/C SK/7 GAF/V1/17.png" },
        { id: 18, img: "/C SK/7 GAF/V1/18.png" },
        { id: 19, img: "/C SK/7 GAF/V1/19.png" },
        { id: 20, img: "/C SK/7 GAF/V1/20.png" },
        { id: 21, img: "/C SK/7 GAF/V1/21.png" },
      ],
      2: [
        { id: 1, img: "/C SK/7 GAF/V2/1.png" },
        { id: 2, img: "/C SK/7 GAF/V2/2.png" },
        { id: 3, img: "/C SK/7 GAF/V2/3.png" },
        { id: 4, img: "/C SK/7 GAF/V2/4.png" },
        { id: 5, img: "/C SK/7 GAF/V2/5.png" },
        { id: 6, img: "/C SK/7 GAF/V2/6.png" },
        { id: 7, img: "/C SK/7 GAF/V2/7.png" },
        { id: 8, img: "/C SK/7 GAF/V2/8.png" },
        { id: 9, img: "/C SK/7 GAF/V2/9.png" },
        { id: 10, img: "/C SK/7 GAF/V2/10.png" },
        { id: 11, img: "/C SK/7 GAF/V2/11.png" },
        { id: 12, img: "/C SK/7 GAF/V2/12.png" },
        { id: 13, img: "/C SK/7 GAF/V2/13.png" },
        { id: 14, img: "/C SK/7 GAF/V2/14.png" },
        { id: 15, img: "/C SK/7 GAF/V2/15.png" },
        { id: 16, img: "/C SK/7 GAF/V2/16.png" },
        { id: 17, img: "/C SK/7 GAF/V2/17.png" },
        { id: 18, img: "/C SK/7 GAF/V2/18.png" },
        { id: 19, img: "/C SK/7 GAF/V2/19.png" },
        { id: 20, img: "/C SK/7 GAF/V2/20.png" },
        { id: 21, img: "/C SK/7 GAF/V2/21.png" },
        { id: 22, img: "/C SK/7 GAF/V2/22.png" },
        { id: 23, img: "/C SK/7 GAF/V2/23.png" },
        { id: 24, img: "/C SK/7 GAF/V2/24.png" },
        { id: 25, img: "/C SK/7 GAF/V2/25.png" },
      ],
      3: [
        { id: 1, img: "/C SK/7 GAF/V3/1.png" },
        { id: 2, img: "/C SK/7 GAF/V3/2.png" },
        { id: 3, img: "/C SK/7 GAF/V3/3.png" },
        { id: 4, img: "/C SK/7 GAF/V3/4.png" },
        { id: 5, img: "/C SK/7 GAF/V3/5.png" },
        { id: 6, img: "/C SK/7 GAF/V3/6.png" },
        { id: 7, img: "/C SK/7 GAF/V3/7.png" },
        { id: 8, img: "/C SK/7 GAF/V3/8.png" },
        { id: 9, img: "/C SK/7 GAF/V3/9.png" },
        { id: 10, img: "/C SK/7 GAF/V3/10.png" },
        { id: 11, img: "/C SK/7 GAF/V3/11.png" },
        { id: 12, img: "/C SK/7 GAF/V3/12.png" },
        { id: 13, img: "/C SK/7 GAF/V3/13.png" },
        { id: 14, img: "/C SK/7 GAF/V3/14.png" },
      ],
    },

    layerToPanelByView: {
      1: {
        1: { zone: "A", panelNum: 1 },
        2: { zone: "A", panelNum: 2 },
        3: { zone: "A", panelNum: 3 },
        4: { zone: "A", panelNum: 4 },
        5: { zone: "B", panelNum: 1 },
        6: { zone: "B", panelNum: 2 },
        7: { zone: "B", panelNum: 3 },
        8: { zone: "B", panelNum: 4 },
        9: { zone: "C", panelNum: 1 },
        10: { zone: "C", panelNum: 2 },
        11: { zone: "C", panelNum: 3 },
        12: { zone: "C", panelNum: 4 },
        13: { zone: "D", panelNum: 1 },
        14: { zone: "D", panelNum: 2 },
        15: { zone: "D", panelNum: 3 },
        16: { zone: "D", panelNum: 4 },
        17: { zone: "E", panelNum: 1 },
        18: { zone: "E", panelNum: 2 },
        19: { zone: "F", panelNum: 1 },

        // ... your current mapping
      },
      2: {
        1: { zone: "A", panelNum: 1 },
        2: { zone: "A", panelNum: 2 },
        3: { zone: "A", panelNum: 3 },
        4: { zone: "A", panelNum: 4 },
        5: { zone: "A", panelNum: 4 },
        6: { zone: "B", panelNum: 1 },
        7: { zone: "B", panelNum: 2 },
        8: { zone: "B", panelNum: 3 },
        9: { zone: "B", panelNum: 4 },
        10: { zone: "B", panelNum: 4 },
        11: { zone: "C", panelNum: 1 },
        12: { zone: "C", panelNum: 2 },
        13: { zone: "C", panelNum: 3 },
        14: { zone: "C", panelNum: 4 },
        15: { zone: "C", panelNum: 4 },
        16: { zone: "D", panelNum: 1 },
        17: { zone: "D", panelNum: 2 },
        18: { zone: "D", panelNum: 3 },
        19: { zone: "D", panelNum: 4 },
        20: { zone: "D", panelNum: 4 },
        21: { zone: "E", panelNum: 1 },
        22: { zone: "E", panelNum: 2 },
        23: { zone: "F", panelNum: 1 },
      },
      3: {
        1: { zone: "A", panelNum: 3 },
        2: { zone: "A", panelNum: 4 },
        3: { zone: "B", panelNum: 3 },
        4: { zone: "B", panelNum: 4 },
        5: { zone: "C", panelNum: 3 },
        6: { zone: "C", panelNum: 4 },
        7: { zone: "D", panelNum: 3 },
        8: { zone: "D", panelNum: 4 },
        9: { zone: "E", panelNum: 1 },
        10: { zone: "E", panelNum: 2 },
        11: { zone: "F", panelNum: 1 },
        12: { zone: "F", panelNum: 2 },
      },
    },

    // ── LEVELe-107 ──
    // Zones: A(4), B(4), C(4), D(4), E(2), F(2)
    // V1: A1→L1..4, B1→L5..8, C1→L9..12, D1→L13..16, E1→L17, E2→L18, F1→L19
    // V3 introduces F2 (layer 12)
    panelMap: {
      A: [
        { layerId: 1, panelNum: 1, top: "28%", left: "28%" },
        { layerId: 2, panelNum: 2, top: "30%", left: "57.5%" },
        { layerId: 3, panelNum: 3, top: "30%", left: "64%" },
        { layerId: 4, panelNum: 4, top: "28%", left: "82%" },
      ],
      B: [
        { layerId: 5, panelNum: 1, top: "42%", left: "28%" },
        { layerId: 6, panelNum: 2, top: "44%", left: "57.5%" },
        { layerId: 7, panelNum: 3, top: "44%", left: "64%" },
        { layerId: 8, panelNum: 4, top: "42%", left: "82%" },
      ],
      C: [
        { layerId: 9, panelNum: 1, top: "55%", left: "28%" },
        { layerId: 10, panelNum: 2, top: "56%", left: "57.5%" },
        { layerId: 11, panelNum: 3, top: "56%", left: "64%" },
        { layerId: 12, panelNum: 4, top: "55%", left: "82%" },
      ],
      D: [
        { layerId: 13, panelNum: 1, top: "70%", left: "28%" },
        { layerId: 14, panelNum: 2, top: "72%", left: "57.5%" },
        { layerId: 15, panelNum: 3, top: "72%", left: "64%" },
        { layerId: 16, panelNum: 4, top: "70%", left: "82%" },
      ],
      E: [
        { layerId: 19, panelNum: 1, top: "24%", left: "61%" },
        { layerId: 20, panelNum: 2, top: "77%", left: "61%" },
      ],
      F: [
        { layerId: 17, panelNum: 1, top: "24%", left: "61%" },
        { layerId: 18, panelNum: 2, top: "77%", left: "61%" },
      ],
    },
  },
  // ────────────────────────────────────────────────
  //                ELX-1108
  // ────────────────────────────────────────────────
  "ELX-1108": {
    name: "ELX-1108",
    skeletonViews: {
      1: [
        { id: 1, img: "/C SK/8 GAF/V1/1.png" },
        { id: 2, img: "/C SK/8 GAF/V1/2.png" },
        { id: 3, img: "/C SK/8 GAF/V1/3.png" },
        { id: 4, img: "/C SK/8 GAF/V1/4.png" },
        { id: 5, img: "/C SK/8 GAF/V1/5.png" },
        { id: 6, img: "/C SK/8 GAF/V1/6.png" },
        { id: 7, img: "/C SK/8 GAF/V1/7.png" },
        { id: 8, img: "/C SK/8 GAF/V1/8.png" },
        { id: 9, img: "/C SK/8 GAF/V1/9.png" },
        { id: 10, img: "/C SK/8 GAF/V1/10.png" },
        { id: 11, img: "/C SK/8 GAF/V1/11.png" },
        { id: 12, img: "/C SK/8 GAF/V1/12.png" },
        { id: 13, img: "/C SK/8 GAF/V1/13.png" },
        { id: 14, img: "/C SK/8 GAF/V1/14.png" },
        { id: 15, img: "/C SK/8 GAF/V1/15.png" },
        { id: 16, img: "/C SK/8 GAF/V1/16.png" },
        { id: 17, img: "/C SK/8 GAF/V1/17.png" },
        { id: 18, img: "/C SK/8 GAF/V1/18.png" },
        { id: 19, img: "/C SK/8 GAF/V1/19.png" },
        { id: 20, img: "/C SK/8 GAF/V1/20.png" },
        { id: 21, img: "/C SK/8 GAF/V1/21.png" },
        { id: 22, img: "/C SK/8 GAF/V1/22.png" },
        { id: 23, img: "/C SK/8 GAF/V1/23.png" },
      ],
      2: [
        { id: 1, img: "/C SK/8 GAF/V2/1.png" },
        { id: 2, img: "/C SK/8 GAF/V2/2.png" },
        { id: 3, img: "/C SK/8 GAF/V2/3.png" },
        { id: 4, img: "/C SK/8 GAF/V2/4.png" },
        { id: 5, img: "/C SK/8 GAF/V2/5.png" },
        { id: 6, img: "/C SK/8 GAF/V2/6.png" },
        { id: 7, img: "/C SK/8 GAF/V2/7.png" },
        { id: 8, img: "/C SK/8 GAF/V2/8.png" },
        { id: 9, img: "/C SK/8 GAF/V2/9.png" },
        { id: 10, img: "/C SK/8 GAF/V2/10.png" },
        { id: 11, img: "/C SK/8 GAF/V2/11.png" },
        { id: 12, img: "/C SK/8 GAF/V2/12.png" },
        { id: 13, img: "/C SK/8 GAF/V2/13.png" },
        { id: 14, img: "/C SK/8 GAF/V2/14.png" },
        { id: 15, img: "/C SK/8 GAF/V2/15.png" },
        { id: 16, img: "/C SK/8 GAF/V2/16.png" },
        { id: 17, img: "/C SK/8 GAF/V2/17.png" },
        { id: 18, img: "/C SK/8 GAF/V2/18.png" },
        { id: 19, img: "/C SK/8 GAF/V2/19.png" },
        { id: 20, img: "/C SK/8 GAF/V2/20.png" },
        { id: 21, img: "/C SK/8 GAF/V2/21.png" },
        { id: 22, img: "/C SK/8 GAF/V2/22.png" },
        { id: 23, img: "/C SK/8 GAF/V2/23.png" },
        { id: 24, img: "/C SK/8 GAF/V2/24.png" },
        { id: 25, img: "/C SK/8 GAF/V2/25.png" },
        { id: 26, img: "/C SK/8 GAF/V2/26.png" },
        { id: 27, img: "/C SK/8 GAF/V2/27.png" },
        { id: 28, img: "/C SK/8 GAF/V2/28.png" },
        { id: 29, img: "/C SK/8 GAF/V2/29.png" },
        { id: 30, img: "/C SK/8 GAF/V2/30.png" },
        { id: 31, img: "/C SK/8 GAF/V2/31.png" },
        { id: 32, img: "/C SK/8 GAF/V2/32.png" },
      ],
      3: [
        { id: 1, img: "/C SK/8 GAF/V3/1.png" },
        { id: 2, img: "/C SK/8 GAF/V3/2.png" },
        { id: 3, img: "/C SK/8 GAF/V3/3.png" },
        { id: 4, img: "/C SK/8 GAF/V3/4.png" },
        { id: 5, img: "/C SK/8 GAF/V3/5.png" },
        { id: 6, img: "/C SK/8 GAF/V3/6.png" },
        { id: 7, img: "/C SK/8 GAF/V3/7.png" },
        { id: 8, img: "/C SK/8 GAF/V3/8.png" },
        { id: 9, img: "/C SK/8 GAF/V3/9.png" },
        { id: 10, img: "/C SK/8 GAF/V3/10.png" },
        { id: 11, img: "/C SK/8 GAF/V3/11.png" },
        { id: 12, img: "/C SK/8 GAF/V3/12.png" },
        { id: 13, img: "/C SK/8 GAF/V3/13.png" },
        { id: 14, img: "/C SK/8 GAF/V3/14.png" },
        { id: 15, img: "/C SK/8 GAF/V3/15.png" },
      ],
    },

    layerToPanelByView: {
      1: {
        1: { zone: "A", panelNum: 1 },
        2: { zone: "A", panelNum: 2 },
        3: { zone: "A", panelNum: 3 },
        4: { zone: "A", panelNum: 4 },
        5: { zone: "B", panelNum: 1 },
        6: { zone: "B", panelNum: 2 },
        7: { zone: "B", panelNum: 3 },
        8: { zone: "B", panelNum: 4 },
        9: { zone: "C", panelNum: 1 },
        10: { zone: "C", panelNum: 2 },
        11: { zone: "D", panelNum: 3 },
        12: { zone: "D", panelNum: 4 },
        13: { zone: "D", panelNum: 1 },
        14: { zone: "D", panelNum: 2 },
        15: { zone: "C", panelNum: 3 },
        16: { zone: "C", panelNum: 4 },
        17: { zone: "E", panelNum: 1 },
        18: { zone: "E", panelNum: 2 },
        19: { zone: "F", panelNum: 1 },
        20: { zone: "F", panelNum: 2 },
        21: { zone: "G", panelNum: 1 },

        // ... your current mapping
      },
      2: {
        1: { zone: "A", panelNum: 1 },
        2: { zone: "A", panelNum: 2 },
        3: { zone: "A", panelNum: 3 },
        4: { zone: "A", panelNum: 3 },
        5: { zone: "A", panelNum: 4 },
        6: { zone: "A", panelNum: 4 },
        7: { zone: "B", panelNum: 1 },
        8: { zone: "B", panelNum: 2 },
        9: { zone: "B", panelNum: 3 },
        10: { zone: "B", panelNum: 3 },
        11: { zone: "B", panelNum: 4 },
        12: { zone: "B", panelNum: 4 },
        13: { zone: "C", panelNum: 1 },
        14: { zone: "C", panelNum: 2 },
        15: { zone: "C", panelNum: 3 },
        16: { zone: "C", panelNum: 3 },
        17: { zone: "C", panelNum: 4 },
        18: { zone: "C", panelNum: 4 },
        19: { zone: "D", panelNum: 1 },
        20: { zone: "D", panelNum: 2 },
        21: { zone: "D", panelNum: 3 },
        22: { zone: "D", panelNum: 3 },
        23: { zone: "D", panelNum: 4 },
        24: { zone: "D", panelNum: 4 },
        25: { zone: "E", panelNum: 1 },
        26: { zone: "E", panelNum: 2 },
        27: { zone: "E", panelNum: 2 },
        28: { zone: "F", panelNum: 1 },
        29: { zone: "F", panelNum: 2 },
        30: { zone: "G", panelNum: 1 },
      },
      3: {
        1: { zone: "A", panelNum: 3 },
        2: { zone: "A", panelNum: 4 },
        3: { zone: "B", panelNum: 3 },
        4: { zone: "B", panelNum: 4 },
        5: { zone: "C", panelNum: 3 },
        6: { zone: "C", panelNum: 4 },
        7: { zone: "D", panelNum: 3 },
        8: { zone: "D", panelNum: 4 },
        9: { zone: "E", panelNum: 2 },
        10: { zone: "F", panelNum: 1 },
        11: { zone: "F", panelNum: 2 },
        12: { zone: "G", panelNum: 1 },
        13: { zone: "G", panelNum: 2 },
      },
    },

    // ── LEVELe-108 ──
    // Zones: A(4), B(4), C(4), D(4), E(2), F(2), G(1)
    // V1: A1→L1..4, B1→L5..8, C1→L9..12, D1→L13..16, E1→L17, E2→L18, F1→L19, F2→L20, G1→L21
    panelMap: {
      A: [
        { layerId: 1, panelNum: 1, top: "30%", left: "18%" },
        { layerId: 2, panelNum: 2, top: "30%", left: "31.5%" },
        { layerId: 3, panelNum: 3, top: "30%", left: "64.2%" },
        { layerId: 4, panelNum: 4, top: "30%", left: "70.6%" },
      ],
      B: [
        { layerId: 5, panelNum: 1, top: "45%", left: "39.6%" },
        { layerId: 6, panelNum: 2, top: "45%", left: "52%" },
        { layerId: 7, panelNum: 3, top: "45%", left: "75.5%" },
        { layerId: 8, panelNum: 4, top: "45%", left: "84%" },
      ],
      C: [
        { layerId: 9, panelNum: 1, top: "65%", left: "18%" },
        { layerId: 10, panelNum: 2, top: "65%", left: "31.5%" },
        { layerId: 11, panelNum: 3, top: "65%", left: "64%" },
        { layerId: 12, panelNum: 4, top: "65%", left: "70%" },
      ],
      D: [
        { layerId: 13, panelNum: 1, top: "70%", left: "39.6%" },
        { layerId: 14, panelNum: 2, top: "70%", left: "52%" },
        { layerId: 15, panelNum: 3, top: "70%", left: "75%" },
        { layerId: 16, panelNum: 4, top: "70%", left: "83%" },
      ],
      E: [                    // ←←← ADD THIS
    { layerId: 17, panelNum: 1, top: "25%", left: "61%" },
    { layerId: 18, panelNum: 2, top: "77%", left: "61%" },
  ],
      
      F: [
        { layerId: 19, panelNum: 1, top: "25%", left: "61%" },
        { layerId: 20, panelNum: 2, top: "77%", left: "61%" },
      ],
      G: [
        { layerId: 21, panelNum: 1, top: "50%", left: "50%" },
        { layerId: 22, panelNum: 2, top: "50%", left: "50%" },

      ],
    },
  },
  // ────────────────────────────────────────────────
  //                RLX-2201
  // ────────────────────────────────────────────────
  "RLX-2201": {
    name: "RLX-2201",
    skeletonViews: {
      1: [
        { id: 1, img: "/C SK/9 GAF/V1/1.png" },
        { id: 2, img: "/C SK/9 GAF/V1/2.png" },
        { id: 3, img: "/C SK/9 GAF/V1/3.png" },
        { id: 4, img: "/C SK/9 GAF/V1/4.png" },
        { id: 5, img: "/C SK/9 GAF/V1/5.png" },
        { id: 6, img: "/C SK/9 GAF/V1/6.png" },
        { id: 7, img: "/C SK/9 GAF/V1/7.png" },
        { id: 8, img: "/C SK/9 GAF/V1/8.png" },
        { id: 9, img: "/C SK/9 GAF/V1/9.png" },
        { id: 10, img: "/C SK/9 GAF/V1/10.png" },
        { id: 11, img: "/C SK/9 GAF/V1/11.png" },
        { id: 12, img: "/C SK/9 GAF/V1/12.png" },
        { id: 13, img: "/C SK/9 GAF/V1/13.png" },
      ],
      2: [
        { id: 1, img: "/C SK/9 GAF/V2/1.png" },
        { id: 2, img: "/C SK/9 GAF/V2/2.png" },
        { id: 3, img: "/C SK/9 GAF/V2/3.png" },
        { id: 4, img: "/C SK/9 GAF/V2/4.png" },
        { id: 5, img: "/C SK/9 GAF/V2/5.png" },
        { id: 6, img: "/C SK/9 GAF/V2/6.png" },
        { id: 7, img: "/C SK/9 GAF/V2/7.png" },
        { id: 8, img: "/C SK/9 GAF/V2/8.png" },
        { id: 9, img: "/C SK/9 GAF/V2/9.png" },
        { id: 10, img: "/C SK/9 GAF/V2/10.png" },
        { id: 11, img: "/C SK/9 GAF/V2/11.png" },
        { id: 12, img: "/C SK/9 GAF/V2/12.png" },
        { id: 13, img: "/C SK/9 GAF/V2/13.png" },
        { id: 14, img: "/C SK/9 GAF/V2/14.png" },
        { id: 15, img: "/C SK/9 GAF/V2/15.png" },
        { id: 16, img: "/C SK/9 GAF/V2/16.png" },
        { id: 17, img: "/C SK/9 GAF/V2/17.png" },
      ],
      3: [
        { id: 1, img: "/C SK/9 GAF/V3/1.png" },
        { id: 2, img: "/C SK/9 GAF/V3/2.png" },
        { id: 3, img: "/C SK/9 GAF/V3/3.png" },
        { id: 4, img: "/C SK/9 GAF/V3/4.png" },
        { id: 5, img: "/C SK/9 GAF/V3/5.png" },
        { id: 6, img: "/C SK/9 GAF/V3/6.png" },
        { id: 7, img: "/C SK/9 GAF/V3/7.png" },
        { id: 8, img: "/C SK/9 GAF/V3/8.png" },
        { id: 9, img: "/C SK/9 GAF/V3/9.png" },
        { id: 10, img: "/C SK/9 GAF/V3/10.png" },
      ],
    },

    layerToPanelByView: {
      1: {
        1: { zone: "A", panelNum: 1 },
        2: { zone: "A", panelNum: 2 },
        3: { zone: "B", panelNum: 1 },
        4: { zone: "B", panelNum: 2 },
        5: { zone: "C", panelNum: 1 },
        6: { zone: "C", panelNum: 2 },
        7: { zone: "D", panelNum: 1 },
        8: { zone: "D", panelNum: 2 },
        9: { zone: "E", panelNum: 1 },
        10: { zone: "E", panelNum: 2 },
        11: { zone: "F", panelNum: 1 },
      },
      2: {
        1: { zone: "A", panelNum: 1 },
        2: { zone: "A", panelNum: 2 },
        3: { zone: "A", panelNum: 2 },
        4: { zone: "B", panelNum: 1 },
        5: { zone: "B", panelNum: 2 },
        6: { zone: "B", panelNum: 2 },
        7: { zone: "C", panelNum: 1 },
        8: { zone: "C", panelNum: 2 },
        9: { zone: "C", panelNum: 2 },
        10: { zone: "D", panelNum: 1 },
        11: { zone: "D", panelNum: 2 },
        12: { zone: "D", panelNum: 2 },
        13: { zone: "E", panelNum: 1 },
        14: { zone: "E", panelNum: 2 },
        15: { zone: "F", panelNum: 1 },
      },
      3: {
        1: { zone: "A", panelNum: 2 },
        2: { zone: "B", panelNum: 2 },
        3: { zone: "C", panelNum: 2 },
        4: { zone: "D", panelNum: 2 },
        5: { zone: "E", panelNum: 1 },
        6: { zone: "E", panelNum: 2 },
        7: { zone: "F", panelNum: 1 },
        8: { zone: "F", panelNum: 2 },
      },
    },

    // ── LEVELe-109 ──
    // Zones: A(2), B(2), C(2), D(2), E(2), F(2)
    // V1: A1→L1, A2→L2, B1→L3, B2→L4, C1→L5, C2→L6, D1→L7, D2→L8, E1→L9, E2→L10, F1→L11
    // V3 introduces F2 (layer 8)
    panelMap: {
      A: [
        { layerId: 1, panelNum: 1, top: "25%", left: "25%" },
        { layerId: 2, panelNum: 2, top: "27%", left: "75%" },
      ],
      B: [
        { layerId: 3, panelNum: 1, top: "37%", left: "25%" },
        { layerId: 4, panelNum: 2, top: "38%", left: "75%" },
      ],
      C: [
        { layerId: 5, panelNum: 1, top: "48%", left: "25%" },
        { layerId: 6, panelNum: 2, top: "50%", left: "75%" },
      ],
      D: [
        { layerId: 7, panelNum: 1, top: "65%", left: "25%" },
        { layerId: 8, panelNum: 2, top: "65%", left: "75%" },
      ],
      E: [
        { layerId: 9, panelNum: 1, top: "25%", left: "61%" },
        { layerId: 10, panelNum: 2, top: "77%", left: "61%" },
      ],
      F: [
        { layerId: 11, panelNum: 1, top: "25%", left: "61%" },
        { layerId: 8, panelNum: 2, top: "77%", left: "61%" },
      ],
    },
  },
  // ────────────────────────────────────────────────
  //                RLX-2202
  // ────────────────────────────────────────────────
  "RLX-2202": {
    name: "RLX-2202",
    skeletonViews: {
      1: [
        { id: 1, img: "/C SK/10 GAF/V1/1.png" },
        { id: 2, img: "/C SK/10 GAF/V1/2.png" },
        { id: 3, img: "/C SK/10 GAF/V1/3.png" },
        { id: 4, img: "/C SK/10 GAF/V1/4.png" },
        { id: 5, img: "/C SK/10 GAF/V1/5.png" },
        { id: 6, img: "/C SK/10 GAF/V1/6.png" },
        { id: 7, img: "/C SK/10 GAF/V1/7.png" },
        { id: 8, img: "/C SK/10 GAF/V1/8.png" },
        { id: 9, img: "/C SK/10 GAF/V1/9.png" },
        { id: 10, img: "/C SK/10 GAF/V1/10.png" },
        { id: 11, img: "/C SK/10 GAF/V1/11.png" },
        { id: 12, img: "/C SK/10 GAF/V1/12.png" },
        { id: 13, img: "/C SK/10 GAF/V1/13.png" },
        { id: 14, img: "/C SK/10 GAF/V1/14.png" },
        { id: 15, img: "/C SK/10 GAF/V1/15.png" },
        { id: 16, img: "/C SK/10 GAF/V1/16.png" },
        { id: 17, img: "/C SK/10 GAF/V1/17.png" },
        { id: 18, img: "/C SK/10 GAF/V1/18.png" },
        { id: 19, img: "/C SK/10 GAF/V1/19.png" },
        { id: 20, img: "/C SK/10 GAF/V1/20.png" },
        { id: 21, img: "/C SK/10 GAF/V1/21.png" },
        { id: 22, img: "/C SK/10 GAF/V1/22.png" },
        { id: 23, img: "/C SK/10 GAF/V1/23.png" },
        { id: 24, img: "/C SK/10 GAF/V1/24.png" },
        { id: 25, img: "/C SK/10 GAF/V1/25.png" },
        { id: 26, img: "/C SK/10 GAF/V1/26.png" },
        { id: 27, img: "/C SK/10 GAF/V1/27.png" },
        { id: 28, img: "/C SK/10 GAF/V1/28.png" },
        { id: 29, img: "/C SK/10 GAF/V1/29.png" },
      ],
      2: [
        { id: 1, img: "/C SK/10 GAF/V2/1.png" },
        { id: 2, img: "/C SK/10 GAF/V2/2.png" },
        { id: 3, img: "/C SK/10 GAF/V2/3.png" },
        { id: 4, img: "/C SK/10 GAF/V2/4.png" },
        { id: 5, img: "/C SK/10 GAF/V2/5.png" },
        { id: 6, img: "/C SK/10 GAF/V2/6.png" },
        { id: 7, img: "/C SK/10 GAF/V2/7.png" },
        { id: 8, img: "/C SK/10 GAF/V2/8.png" },
        { id: 9, img: "/C SK/10 GAF/V2/9.png" },
        { id: 10, img: "/C SK/10 GAF/V2/10.png" },
        { id: 11, img: "/C SK/10 GAF/V2/11.png" },
        { id: 12, img: "/C SK/10 GAF/V2/12.png" },
        { id: 13, img: "/C SK/10 GAF/V2/13.png" },
        { id: 14, img: "/C SK/10 GAF/V2/14.png" },
        { id: 15, img: "/C SK/10 GAF/V2/15.png" },
        { id: 16, img: "/C SK/10 GAF/V2/16.png" },
        { id: 17, img: "/C SK/10 GAF/V2/17.png" },
        { id: 18, img: "/C SK/10 GAF/V2/18.png" },
        { id: 19, img: "/C SK/10 GAF/V2/19.png" },
        { id: 20, img: "/C SK/10 GAF/V2/20.png" },
        { id: 21, img: "/C SK/10 GAF/V2/21.png" },
        { id: 22, img: "/C SK/10 GAF/V2/22.png" },
        { id: 23, img: "/C SK/10 GAF/V2/23.png" },
        { id: 24, img: "/C SK/10 GAF/V2/24.png" },
        { id: 25, img: "/C SK/10 GAF/V2/25.png" },
        { id: 26, img: "/C SK/10 GAF/V2/26.png" },
        { id: 27, img: "/C SK/10 GAF/V2/27.png" },
        { id: 28, img: "/C SK/10 GAF/V2/28.png" },
        { id: 29, img: "/C SK/10 GAF/V2/29.png" },
        { id: 30, img: "/C SK/10 GAF/V2/30.png" },
        { id: 31, img: "/C SK/10 GAF/V2/31.png" },
        { id: 32, img: "/C SK/10 GAF/V2/32.png" },
        { id: 33, img: "/C SK/10 GAF/V2/33.png" },
        { id: 34, img: "/C SK/10 GAF/V2/34.png" },
        { id: 35, img: "/C SK/10 GAF/V2/35.png" },
        { id: 36, img: "/C SK/10 GAF/V2/36.png" },
        { id: 37, img: "/C SK/10 GAF/V2/37.png" },
        { id: 38, img: "/C SK/10 GAF/V2/38.png" },
        { id: 39, img: "/C SK/10 GAF/V2/39.png" },
        { id: 40, img: "/C SK/10 GAF/V2/40.png" },
        { id: 41, img: "/C SK/10 GAF/V2/41.png" },
      ],
      3: [
        { id: 1, img: "/C SK/10 GAF/V3/1.png" },
        { id: 2, img: "/C SK/10 GAF/V3/2.png" },
        { id: 3, img: "/C SK/10 GAF/V3/3.png" },
        { id: 4, img: "/C SK/10 GAF/V3/4.png" },
        { id: 5, img: "/C SK/10 GAF/V3/5.png" },
        { id: 6, img: "/C SK/10 GAF/V3/6.png" },
        { id: 7, img: "/C SK/10 GAF/V3/7.png" },
        { id: 8, img: "/C SK/10 GAF/V3/8.png" },
        { id: 9, img: "/C SK/10 GAF/V3/9.png" },
        { id: 10, img: "/C SK/10 GAF/V3/10.png" },
        { id: 11, img: "/C SK/10 GAF/V3/11.png" },
        { id: 12, img: "/C SK/10 GAF/V3/12.png" },
        { id: 13, img: "/C SK/10 GAF/V3/13.png" },
        { id: 14, img: "/C SK/10 GAF/V3/14.png" },
        { id: 15, img: "/C SK/10 GAF/V3/15.png" },
        { id: 16, img: "/C SK/10 GAF/V3/16.png" },
        { id: 17, img: "/C SK/10 GAF/V3/17.png" },
        { id: 18, img: "/C SK/10 GAF/V3/18.png" },
      ],
    },

    layerToPanelByView: {
      1: {
        1: { zone: "A", panelNum: 1 },
        2: { zone: "A", panelNum: 2 },
        3: { zone: "A", panelNum: 3 },
        4: { zone: "A", panelNum: 4 },
        5: { zone: "A", panelNum: 5 },
        6: { zone: "A", panelNum: 6 },
        7: { zone: "B", panelNum: 1 },
        8: { zone: "B", panelNum: 2 },
        9: { zone: "B", panelNum: 3 },
        10: { zone: "B", panelNum: 4 },
        11: { zone: "B", panelNum: 5 },
        12: { zone: "B", panelNum: 6 },
        13: { zone: "C", panelNum: 1 },
        14: { zone: "C", panelNum: 2 },
        15: { zone: "C", panelNum: 3 },
        16: { zone: "C", panelNum: 4 },
        17: { zone: "C", panelNum: 5 },
        18: { zone: "C", panelNum: 6 },
        19: { zone: "D", panelNum: 1 },
        20: { zone: "D", panelNum: 2 },
        21: { zone: "D", panelNum: 3 },
        22: { zone: "D", panelNum: 4 },
        23: { zone: "D", panelNum: 5 },
        24: { zone: "D", panelNum: 6 },
        25: { zone: "E", panelNum: 1 },
        26: { zone: "E", panelNum: 2 },
        27: { zone: "F", panelNum: 1 },
        // ... your current mapping
      },
      2: {
        1: { zone: "A", panelNum: 1 },
        2: { zone: "A", panelNum: 4 },
        3: { zone: "A", panelNum: 4 },
        4: { zone: "A", panelNum: 2 },
        5: { zone: "A", panelNum: 5 },
        6: { zone: "A", panelNum: 5 },
        7: { zone: "A", panelNum: 3 },
        8: { zone: "A", panelNum: 6 },
        9: { zone: "A", panelNum: 6 },
        10: { zone: "B", panelNum: 1 },
        11: { zone: "B", panelNum: 4 },
        12: { zone: "B", panelNum: 4 },
        13: { zone: "B", panelNum: 2 },
        14: { zone: "B", panelNum: 5 },
        15: { zone: "B", panelNum: 5 },
        16: { zone: "B", panelNum: 3 },
        17: { zone: "B", panelNum: 6 },
        18: { zone: "B", panelNum: 6 },
        19: { zone: "C", panelNum: 1 },
        20: { zone: "C", panelNum: 4 },
        21: { zone: "C", panelNum: 4 },
        22: { zone: "C", panelNum: 2 },
        23: { zone: "C", panelNum: 5 },
        24: { zone: "C", panelNum: 5 },
        25: { zone: "C", panelNum: 3 },
        26: { zone: "C", panelNum: 6 },
        27: { zone: "C", panelNum: 6 },
        28: { zone: "D", panelNum: 1 },
        29: { zone: "D", panelNum: 4 },
        30: { zone: "D", panelNum: 4 },
        31: { zone: "D", panelNum: 2 },
        32: { zone: "D", panelNum: 5 },
        33: { zone: "D", panelNum: 5 },
        34: { zone: "D", panelNum: 3 },
        35: { zone: "D", panelNum: 6 },
        36: { zone: "D", panelNum: 6 },
        37: { zone: "E", panelNum: 1 },
        38: { zone: "E", panelNum: 2 },
        39: { zone: "F", panelNum: 1 },
      },
      3: {
        1: { zone: "A", panelNum: 4 },
        2: { zone: "A", panelNum: 5 },
        3: { zone: "A", panelNum: 6 },
        4: { zone: "B", panelNum: 4 },
        5: { zone: "B", panelNum: 5 },
        6: { zone: "B", panelNum: 6 },
        7: { zone: "C", panelNum: 4 },
        8: { zone: "C", panelNum: 5 },
        9: { zone: "C", panelNum: 6 },
        10: { zone: "D", panelNum: 4 },
        11: { zone: "D", panelNum: 5 },
        12: { zone: "D", panelNum: 6 },
        13: { zone: "E", panelNum: 1 },
        14: { zone: "E", panelNum: 2 },
        15: { zone: "F", panelNum: 1 },
        16: { zone: "F", panelNum: 1 },
      },
    },

    // ── LEVELe-110 ──
    // Zones: A(6), B(6), C(6), D(6), E(2), F(1)
    // V1: A1→L1..6, B1→L7..12, C1→L13..18, D1→L19..24, E1→L25, E2→L26, F1→L27
    panelMap: {
      A: [
        { layerId: 1, panelNum: 1, top: "26%", left: "17%" },
        { layerId: 2, panelNum: 2, top: "28%", left: "38%" },
        { layerId: 3, panelNum: 3, top: "30%", left: "56%" },
        { layerId: 4, panelNum: 4, top: "30%", left: "63.5%" },
        { layerId: 5, panelNum: 5, top: "28%", left: "74%" },
        { layerId: 6, panelNum: 6, top: "26%", left: "86%" },
      ],
      B: [
        { layerId: 7, panelNum: 1, top: "42%", left: "17%" },
        { layerId: 8, panelNum: 2, top: "43%", left: "38%" },
        { layerId: 9, panelNum: 3, top: "44%", left: "56%" },
        { layerId: 10, panelNum: 4, top: "44%", left: "63.5%" },
        { layerId: 11, panelNum: 5, top: "43%", left: "74%" },
        { layerId: 12, panelNum: 6, top: "42%", left: "86%" },
      ],
      C: [
        { layerId: 13, panelNum: 1, top: "58%", left: "17%" },
        { layerId: 14, panelNum: 2, top: "58%", left: "38%" },
        { layerId: 15, panelNum: 3, top: "58%", left: "56%" },
        { layerId: 16, panelNum: 4, top: "58%", left: "63.5%" },
        { layerId: 17, panelNum: 5, top: "58%", left: "74%" },
        { layerId: 18, panelNum: 6, top: "58%", left: "86%" },
      ],
      D: [
        { layerId: 19, panelNum: 1, top: "74%", left: "17%" },
        { layerId: 20, panelNum: 2, top: "72%", left: "38%" },
        { layerId: 21, panelNum: 3, top: "70%", left: "56%" },
        { layerId: 22, panelNum: 4, top: "70%", left: "63.5%" },
        { layerId: 23, panelNum: 5, top: "71%", left: "74%" },
        { layerId: 24, panelNum: 6, top: "73%", left: "86%" },
      ],
      E: [
        { layerId: 25, panelNum: 1, top: "24%", left: "61%" },
        { layerId: 27, panelNum: 2, top: "77%", left: "61%" },
      ],
      F: [{ layerId: 26, panelNum: 1, top: "77%", left: "61%" }],
    },
  },
  // ────────────────────────────────────────────────
  //                RLX-2203
  // ────────────────────────────────────────────────
  "RLX-2203": {
    name: "RLX-2203",
    skeletonViews: {
      1: [
        { id: 1, img: "/C SK/11 GAF/V1/1.png" },
        { id: 2, img: "/C SK/11 GAF/V1/2.png" },
        { id: 3, img: "/C SK/11 GAF/V1/3.png" },
        { id: 4, img: "/C SK/11 GAF/V1/4.png" },
        { id: 5, img: "/C SK/11 GAF/V1/5.png" },
        { id: 6, img: "/C SK/11 GAF/V1/6.png" },
        { id: 7, img: "/C SK/11 GAF/V1/7.png" },
        { id: 8, img: "/C SK/11 GAF/V1/8.png" },
        { id: 9, img: "/C SK/11 GAF/V1/9.png" },
        { id: 10, img: "/C SK/11 GAF/V1/10.png" },
        { id: 11, img: "/C SK/11 GAF/V1/11.png" },
        { id: 12, img: "/C SK/11 GAF/V1/12.png" },
        { id: 13, img: "/C SK/11 GAF/V1/13.png" },
        { id: 14, img: "/C SK/11 GAF/V1/14.png" },
        { id: 15, img: "/C SK/11 GAF/V1/15.png" },
        { id: 16, img: "/C SK/11 GAF/V1/16.png" },
        { id: 17, img: "/C SK/11 GAF/V1/17.png" },
        { id: 18, img: "/C SK/11 GAF/V1/18.png" },
        { id: 19, img: "/C SK/11 GAF/V1/19.png" },
        { id: 20, img: "/C SK/11 GAF/V1/20.png" },
      ],
      2: [
        { id: 1, img: "/C SK/11 GAF/V2/1.png" },
        { id: 2, img: "/C SK/11 GAF/V2/2.png" },
        { id: 3, img: "/C SK/11 GAF/V2/3.png" },
        { id: 4, img: "/C SK/11 GAF/V2/4.png" },
        { id: 5, img: "/C SK/11 GAF/V2/5.png" },
        { id: 6, img: "/C SK/11 GAF/V2/6.png" },
        { id: 7, img: "/C SK/11 GAF/V2/7.png" },
        { id: 8, img: "/C SK/11 GAF/V2/8.png" },
        { id: 9, img: "/C SK/11 GAF/V2/9.png" },
        { id: 10, img: "/C SK/11 GAF/V2/10.png" },
        { id: 11, img: "/C SK/11 GAF/V2/11.png" },
        { id: 12, img: "/C SK/11 GAF/V2/12.png" },
        { id: 13, img: "/C SK/11 GAF/V2/13.png" },
        { id: 14, img: "/C SK/11 GAF/V2/14.png" },
        { id: 15, img: "/C SK/11 GAF/V2/15.png" },
        { id: 16, img: "/C SK/11 GAF/V2/16.png" },
        { id: 17, img: "/C SK/11 GAF/V2/17.png" },
        { id: 18, img: "/C SK/11 GAF/V2/18.png" },
        { id: 19, img: "/C SK/11 GAF/V2/19.png" },
        { id: 20, img: "/C SK/11 GAF/V2/20.png" },
        { id: 21, img: "/C SK/11 GAF/V2/21.png" },
        { id: 22, img: "/C SK/11 GAF/V2/22.png" },
        { id: 23, img: "/C SK/11 GAF/V2/23.png" },
        { id: 24, img: "/C SK/11 GAF/V2/24.png" },
        { id: 25, img: "/C SK/11 GAF/V2/25.png" },
      ],
      3: [
        { id: 1, img: "/C SK/11 GAF/V3/1.png" },
        { id: 2, img: "/C SK/11 GAF/V3/2.png" },
        { id: 3, img: "/C SK/11 GAF/V3/3.png" },
        { id: 4, img: "/C SK/11 GAF/V3/4.png" },
        { id: 5, img: "/C SK/11 GAF/V3/5.png" },
        { id: 6, img: "/C SK/11 GAF/V3/6.png" },
        { id: 7, img: "/C SK/11 GAF/V3/7.png" },
        { id: 8, img: "/C SK/11 GAF/V3/8.png" },
        { id: 9, img: "/C SK/11 GAF/V3/9.png" },
        { id: 10, img: "/C SK/11 GAF/V3/10.png" },
        { id: 11, img: "/C SK/11 GAF/V3/11.png" },
      ],
    },

    layerToPanelByView: {
      1: {
        1: { zone: "A", panelNum: 1 },
        2: { zone: "A", panelNum: 2 },
        3: { zone: "A", panelNum: 3 },
        4: { zone: "B", panelNum: 1 },
        5: { zone: "B", panelNum: 2 },
        6: { zone: "B", panelNum: 3 },
        7: { zone: "C", panelNum: 1 },
        8: { zone: "C", panelNum: 2 },
        9: { zone: "C", panelNum: 3 },
        10: { zone: "D", panelNum: 1 },
        11: { zone: "D", panelNum: 2 },
        12: { zone: "D", panelNum: 3 },
        13: { zone: "E", panelNum: 1 },
        14: { zone: "E", panelNum: 2 },
        15: { zone: "E", panelNum: 3 },
        16: { zone: "F", panelNum: 1 },
        17: { zone: "F", panelNum: 2 },
        18: { zone: "G", panelNum: 1 },

        // ... your current mapping
      },
      2: {
        1: { zone: "A", panelNum: 1 },
        2: { zone: "A", panelNum: 2 },
        3: { zone: "A", panelNum: 3 },
        4: { zone: "A", panelNum: 3 },
        5: { zone: "B", panelNum: 1 },
        6: { zone: "B", panelNum: 2 },
        7: { zone: "B", panelNum: 3 },
        8: { zone: "B", panelNum: 3 },
        9: { zone: "C", panelNum: 1 },
        10: { zone: "C", panelNum: 2 },
        11: { zone: "C", panelNum: 3 },
        12: { zone: "C", panelNum: 3 },
        13: { zone: "D", panelNum: 1 },
        14: { zone: "D", panelNum: 2 },
        15: { zone: "D", panelNum: 3 },
        16: { zone: "D", panelNum: 3 },
        17: { zone: "E", panelNum: 1 },
        18: { zone: "E", panelNum: 2 },
        19: { zone: "E", panelNum: 3 },
        20: { zone: "E", panelNum: 3 },
        21: { zone: "F", panelNum: 1 },
        22: { zone: "F", panelNum: 2 },
        23: { zone: "G", panelNum: 1 },
      },
      3: {
        1: { zone: "A", panelNum: 3 },
        2: { zone: "B", panelNum: 3 },
        3: { zone: "C", panelNum: 3 },
        4: { zone: "D", panelNum: 3 },
        5: { zone: "E", panelNum: 3 },
        6: { zone: "F", panelNum: 1 },
        7: { zone: "F", panelNum: 2 },
        8: { zone: "G", panelNum: 1 },
        9: { zone: "G", panelNum: 2 },
      },
    },

    // ── LEVELe-111 ──
    // Zones: A(3), B(3), C(3), D(3), E(3), F(2), G(2)
    // V1: A1→L1, A2→L2, A3→L3, B1→L4, B2→L5, B3→L6, C1→L7, C2→L8, C3→L9,
    //     D1→L10, D2→L11, D3→L12, E1→L13, E2→L14, E3→L15, F1→L16, F2→L17, G1→L18
    // V3 introduces G2 (layer 9 from V3 mapping)
    panelMap: {
      A: [
        { layerId: 1, panelNum: 1, top: "25%", left: "16%" },
        { layerId: 2, panelNum: 2, top: "29%", left: "43%" },
        { layerId: 3, panelNum: 3, top: "28%", left: "75%" },
      ],
      B: [
        { layerId: 4, panelNum: 1, top: "37%", left: "16%" },
        { layerId: 5, panelNum: 2, top: "38%", left: "43%" },
        { layerId: 6, panelNum: 3, top: "38%", left: "75%" },
      ],
      C: [
        { layerId: 7, panelNum: 1, top: "50%", left: "16%" },
        { layerId: 8, panelNum: 2, top: "50%", left: "43%" },
        { layerId: 9, panelNum: 3, top: "50%", left: "75%" },
      ],
      D: [
        { layerId: 10, panelNum: 1, top: "63%", left: "16%" },
        { layerId: 11, panelNum: 2, top: "63%", left: "43%" },
        { layerId: 12, panelNum: 3, top: "63%", left: "75%" },
      ],
      E: [
        { layerId: 13, panelNum: 1, top: "76%", left: "16%" },
        { layerId: 14, panelNum: 2, top: "74%", left: "43%" },
        { layerId: 15, panelNum: 3, top: "73%", left: "75%" },
      ],
      F: [
        { layerId: 16, panelNum: 1, top: "24%", left: "61%" },
        { layerId: 17, panelNum: 2, top: "77%", left: "61%" },
      ],
      G: [
        { layerId: 18, panelNum: 1, top: "24%", left: "61%" },
        { layerId: 9, panelNum: 2, top: "77%", left: "61%" },
      ],
    },
  },
  // ────────────────────────────────────────────────
  //                RLX-2204
  // ────────────────────────────────────────────────
  "RLX-2204": {
    name: "RLX-2204",
    skeletonViews: {
      1: [
        { id: 1, img: "/C SK/12 GAF/V1/1.png" },
        { id: 2, img: "/C SK/12 GAF/V1/2.png" },
        { id: 3, img: "/C SK/12 GAF/V1/3.png" },
        { id: 4, img: "/C SK/12 GAF/V1/4.png" },
        { id: 5, img: "/C SK/12 GAF/V1/5.png" },
        { id: 6, img: "/C SK/12 GAF/V1/6.png" },
        { id: 7, img: "/C SK/12 GAF/V1/7.png" },
        { id: 8, img: "/C SK/12 GAF/V1/8.png" },
        { id: 9, img: "/C SK/12 GAF/V1/9.png" },
        { id: 10, img: "/C SK/12 GAF/V1/10.png" },
      ],
      2: [
        { id: 1, img: "/C SK/12 GAF/V2/1.png" },
        { id: 2, img: "/C SK/12 GAF/V2/2.png" },
        { id: 3, img: "/C SK/12 GAF/V2/3.png" },
        { id: 4, img: "/C SK/12 GAF/V2/4.png" },
        { id: 5, img: "/C SK/12 GAF/V2/5.png" },
        { id: 6, img: "/C SK/12 GAF/V2/6.png" },
        { id: 7, img: "/C SK/12 GAF/V2/7.png" },
        { id: 8, img: "/C SK/12 GAF/V2/8.png" },
        { id: 9, img: "/C SK/12 GAF/V2/9.png" },
        { id: 10, img: "/C SK/12 GAF/V2/10.png" },
        { id: 11, img: "/C SK/12 GAF/V2/11.png" },
        { id: 12, img: "/C SK/12 GAF/V2/12.png" },
        { id: 13, img: "/C SK/12 GAF/V2/13.png" },
      ],
      3: [
        { id: 1, img: "/C SK/12 GAF/V3/1.png" },
        { id: 2, img: "/C SK/12 GAF/V3/2.png" },
        { id: 3, img: "/C SK/12 GAF/V3/3.png" },
        { id: 4, img: "/C SK/12 GAF/V3/4.png" },
        { id: 5, img: "/C SK/12 GAF/V3/5.png" },
        { id: 6, img: "/C SK/12 GAF/V3/6.png" },
        { id: 7, img: "/C SK/12 GAF/V3/7.png" },
        { id: 8, img: "/C SK/12 GAF/V3/8.png" },
        { id: 9, img: "/C SK/12 GAF/V3/9.png" },
      ],
    },

    layerToPanelByView: {
      1: {
        1: { zone: "A", panelNum: 1 },
        2: { zone: "A", panelNum: 2 },
        3: { zone: "A", panelNum: 3 },
        4: { zone: "B", panelNum: 1 },
        5: { zone: "B", panelNum: 2 },
        6: { zone: "C", panelNum: 1 },
        7: { zone: "C", panelNum: 2 },
        8: { zone: "D", panelNum: 1 },

        // ... your current mapping
      },
      2: {
        1: { zone: "A", panelNum: 1 },
        2: { zone: "A", panelNum: 2 },
        3: { zone: "A", panelNum: 2 },
        4: { zone: "A", panelNum: 3 },
        5: { zone: "A", panelNum: 3 },
        6: { zone: "B", panelNum: 1 },
        7: { zone: "B", panelNum: 2 },
        8: { zone: "B", panelNum: 2 },
        9: { zone: "C", panelNum: 1 },
        10: { zone: "C", panelNum: 2 },
        11: { zone: "D", panelNum: 1 },
      },
      3: {
        1: { zone: "A", panelNum: 2 },
        2: { zone: "A", panelNum: 3 },
        3: { zone: "B", panelNum: 2 },
        4: { zone: "C", panelNum: 1 },
        5: { zone: "C", panelNum: 2 },
        6: { zone: "D", panelNum: 1 },
        7: { zone: "D", panelNum: 2 },
      },
    },
    // ── LEVELe-112 ──
    // Zones: A(3), B(3), C(2), D(2)
    // V1: A1→L1, A2→L2, A3→L3, B1→L4, B2→L5, C1→L6, C2→L7, D1→L8
    // V2 introduces B3→L8, V3 introduces D2→L7
    panelMap: {
      A: [
        { layerId: 1, panelNum: 1, top: "40%", left: "38%" },
        { layerId: 2, panelNum: 2, top: "30%", left: "75%" },
        { layerId: 3, panelNum: 3, top: "48%", left: "75%" },
      ],
      B: [
        { layerId: 4, panelNum: 1, top: "70%", left: "38%" },
        { layerId: 5, panelNum: 2, top: "70%", left: "75%" },
      ],
      C: [
        { layerId: 8, panelNum: 1, top: "25%", left: "61%" },
        { layerId: 9, panelNum: 2, top: "77%", left: "61%" },
      ],
      D: [
        { layerId: 6, panelNum: 1, top: "25%", left: "61%" },
        { layerId: 7, panelNum: 2, top: "77%", left: "61%" },
      ],
    },
  },
  // ────────────────────────────────────────────────
  //                RLX-2205
  // ────────────────────────────────────────────────
  "RLX-2205": {
    name: "RLX-2205",
    skeletonViews: {
      1: [
        { id: 1, img: "/C SK/13 GAF/V1/1.png" },
        { id: 2, img: "/C SK/13 GAF/V1/2.png" },
        { id: 3, img: "/C SK/13 GAF/V1/3.png" },
        { id: 4, img: "/C SK/13 GAF/V1/4.png" },
        { id: 5, img: "/C SK/13 GAF/V1/5.png" },
        { id: 6, img: "/C SK/13 GAF/V1/6.png" },
        { id: 7, img: "/C SK/13 GAF/V1/7.png" },
        { id: 8, img: "/C SK/13 GAF/V1/8.png" },
        { id: 9, img: "/C SK/13 GAF/V1/9.png" },
        { id: 10, img: "/C SK/13 GAF/V1/10.png" },
      ],
      2: [
        { id: 1, img: "/C SK/13 GAF/V2/1.png" },
        { id: 2, img: "/C SK/13 GAF/V2/2.png" },
        { id: 3, img: "/C SK/13 GAF/V2/3.png" },
        { id: 4, img: "/C SK/13 GAF/V2/4.png" },
        { id: 5, img: "/C SK/13 GAF/V2/5.png" },
        { id: 6, img: "/C SK/13 GAF/V2/6.png" },
        { id: 7, img: "/C SK/13 GAF/V2/7.png" },
        { id: 8, img: "/C SK/13 GAF/V2/8.png" },
        { id: 9, img: "/C SK/13 GAF/V2/9.png" },
        { id: 10, img: "/C SK/13 GAF/V2/10.png" },
        { id: 11, img: "/C SK/13 GAF/V2/11.png" },
        { id: 12, img: "/C SK/13 GAF/V2/12.png" },
      ],
      3: [
        { id: 1, img: "/C SK/13 GAF/V3/1.png" },
        { id: 2, img: "/C SK/13 GAF/V3/2.png" },
        { id: 3, img: "/C SK/13 GAF/V3/3.png" },
        { id: 4, img: "/C SK/13 GAF/V3/4.png" },
        { id: 5, img: "/C SK/13 GAF/V3/5.png" },
        { id: 6, img: "/C SK/13 GAF/V3/6.png" },
        { id: 7, img: "/C SK/13 GAF/V3/7.png" },
        { id: 8, img: "/C SK/13 GAF/V3/8.png" },
      ],
    },

    layerToPanelByView: {
      1: {
        1: { zone: "A", panelNum: 1 },
        2: { zone: "A", panelNum: 2 },
        3: { zone: "A", panelNum: 3 },
        4: { zone: "B", panelNum: 1 },
        5: { zone: "B", panelNum: 2 },
        6: { zone: "C", panelNum: 1 },
        7: { zone: "C", panelNum: 2 },
        8: { zone: "D", panelNum: 1 },

        // ... your current mapping
      },
      2: {
        1: { zone: "A", panelNum: 1 },
        2: { zone: "A", panelNum: 2 },
        3: { zone: "A", panelNum: 3 },
        4: { zone: "B", panelNum: 1 },
        5: { zone: "B", panelNum: 1 },
        6: { zone: "B", panelNum: 2 },
        7: { zone: "B", panelNum: 2 },
        8: { zone: "C", panelNum: 1 },
        9: { zone: "C", panelNum: 2 },
        10: { zone: "D", panelNum: 1 },
      },
      3: {
        1: { zone: "B", panelNum: 1 },
        2: { zone: "B", panelNum: 2 },
        3: { zone: "C", panelNum: 1 },
        4: { zone: "C", panelNum: 2 },
        5: { zone: "D", panelNum: 1 },
        6: { zone: "D", panelNum: 2 },
      },
    },
    // ── LEVELe-113 ──
    // Zones: A(3), B(2), C(2), D(1)
    // V1: A1→L1, A2→L2, A3→L3, B1→L4, B2→L5, C1→L6, C2→L7, D1→L8
    // V3 introduces D2→L6
    panelMap: {
      A: [
        { layerId: 1, panelNum: 1, top: "30%", left: "20%" },
        { layerId: 2, panelNum: 2, top: "40%", left: "40%" },
        { layerId: 3, panelNum: 3, top: "50%", left: "55%" },
      ],
      B: [
        { layerId: 4, panelNum: 1, top: "60%", left: "67%" },
        { layerId: 5, panelNum: 2, top: "70%", left: "80%" },
      ],
      C: [
        { layerId: 8, panelNum: 1, top: "25%", left: "61%" },
        { layerId: 9, panelNum: 2, top: "77%", left: "61%" },
      ],
      D: [
        { layerId: 6, panelNum: 1, top: "25%", left: "61%" },
        { layerId: 7, panelNum: 2, top: "77%", left: "61%" },
      ],
    },
  },
  // ────────────────────────────────────────────────
  //                CLX-3301
  // ────────────────────────────────────────────────
 "CLX-3301": {
  name: "CLX-3301",
  skeletonViews: {
    1: [
      { id: 1, img: "/C SK/14 GAF/V1/1.png" },
      { id: 2, img: "/C SK/14 GAF/V1/2.png" },
      { id: 3, img: "/C SK/14 GAF/V1/3.png" },
      { id: 4, img: "/C SK/14 GAF/V1/4.png" },
      { id: 5, img: "/C SK/14 GAF/V1/5.png" },
      { id: 6, img: "/C SK/14 GAF/V1/6.png" },
      { id: 7, img: "/C SK/14 GAF/V1/7.png" },
      { id: 8, img: "/C SK/14 GAF/V1/8.png" },
      { id: 9, img: "/C SK/14 GAF/V1/9.png" },
      { id: 10, img: "/C SK/14 GAF/V1/10.png" },
      { id: 11, img: "/C SK/14 GAF/V1/11.png" },
      { id: 12, img: "/C SK/14 GAF/V1/12.png" },
      { id: 13, img: "/C SK/14 GAF/V1/13.png" },
    ],
    2: [
      { id: 1, img: "/C SK/14 GAF/V2/1.png" },
      { id: 2, img: "/C SK/14 GAF/V2/2.png" },
      { id: 3, img: "/C SK/14 GAF/V2/3.png" },
      { id: 4, img: "/C SK/14 GAF/V2/4.png" },
      { id: 5, img: "/C SK/14 GAF/V2/5.png" },
      { id: 6, img: "/C SK/14 GAF/V2/6.png" },
      { id: 7, img: "/C SK/14 GAF/V2/7.png" },
      { id: 8, img: "/C SK/14 GAF/V2/8.png" },
      { id: 9, img: "/C SK/14 GAF/V2/9.png" },
      { id: 10, img: "/C SK/14 GAF/V2/10.png" },
      { id: 11, img: "/C SK/14 GAF/V2/11.png" },
      { id: 12, img: "/C SK/14 GAF/V2/12.png" },
      { id: 13, img: "/C SK/14 GAF/V2/13.png" },
      { id: 14, img: "/C SK/14 GAF/V2/14.png" },
      { id: 15, img: "/C SK/14 GAF/V2/15.png" },
      { id: 16, img: "/C SK/14 GAF/V2/16.png" },
    ],
    3: [
      { id: 1, img: "/C SK/14 GAF/V3/1.png" },
      { id: 2, img: "/C SK/14 GAF/V3/2.png" },
      { id: 3, img: "/C SK/14 GAF/V3/3.png" },
      { id: 4, img: "/C SK/14 GAF/V3/4.png" },
      { id: 5, img: "/C SK/14 GAF/V3/5.png" },
      { id: 6, img: "/C SK/14 GAF/V3/6.png" },
      { id: 7, img: "/C SK/14 GAF/V3/7.png" },
      { id: 8, img: "/C SK/14 GAF/V3/8.png" },
      { id: 9, img: "/C SK/14 GAF/V3/9.png" },
      { id: 10, img: "/C SK/14 GAF/V3/10.png" },
    ],
  },

  layerToPanelByView: {
    1: {
      1: { zone: "A", panelNum: 1 },
      2: { zone: "A", panelNum: 2 },
      3: { zone: "A", panelNum: 3 },
      4: { zone: "B", panelNum: 1 },
      5: { zone: "B", panelNum: 2 },
      6: { zone: "C", panelNum: 1 },
      7: { zone: "C", panelNum: 2 },
      8: { zone: "D", panelNum: 1 },
      9: { zone: "D", panelNum: 2 },
      10: { zone: "E", panelNum: 1 },
      11: { zone: "E", panelNum: 2 },

    },
    2: {
      1: { zone: "B", panelNum: 2 },
      2: { zone: "C", panelNum: 1 },
      3: { zone: "C", panelNum: 2 },
      4: { zone: "B", panelNum: 1 },
      5: { zone: "A", panelNum: 1 },
      6: { zone: "A", panelNum: 2 },
      7: { zone: "A", panelNum: 3 },
      8: { zone: "B", panelNum: 2 },
      9: { zone: "C", panelNum: 1 },
      10: { zone: "C", panelNum: 2 },
      11: { zone: "D", panelNum: 1 },
      12: { zone: "D", panelNum: 2 },
      13: { zone: "E", panelNum: 1 },
      14: { zone: "E", panelNum: 2 },
      15: { zone: "E", panelNum: 2 },
      // 16: { zone: "F", panelNum: 1 },
    },
    3: {
      1: { zone: "B", panelNum: 2 },
      2: { zone: "C", panelNum: 1 },
      3: { zone: "C", panelNum: 2 },
      4: { zone: "D", panelNum: 1 },
      5: { zone: "D", panelNum: 2 },
      6: { zone: "E", panelNum: 2 },
      7: { zone: "E", panelNum: 1 },
      8: { zone: "D", panelNum: 2 },
      9: { zone: "A", panelNum: 3 },   // Adjust if needed
      10: { zone: "A", panelNum: 2 },
    },
  },

  // ── LEVELc-301 ──
  // Zones: A(3), B(2), C(3), D(2), E(2), F(2)
  panelMap: {
    A: [
      { layerId: 1, panelNum: 1, top: "40%", left: "20%" },
      { layerId: 2, panelNum: 2, top: "41%", left: "38%" },
      { layerId: 3, panelNum: 3, top: "42%", left: "54%" },
    ],
    B: [
      { layerId: 4, panelNum: 1, top: "70%", left: "38%" },
      { layerId: 5, panelNum: 2, top: "70%", left: "73%" },
    ],
    C: [
      { layerId: 6, panelNum: 1, top: "50%", left: "67%" },
      { layerId: 7, panelNum: 2, top: "50%", left: "80%" },
    ],
    D: [
      { layerId: 9, panelNum: 1, top: "25%", left: "61%" },
      { layerId: 10, panelNum: 2, top: "77%", left: "61%" },
    ],
    E: [
      { layerId: 10, panelNum: 1, top: "25%", left: "61%" },   // Fixed layerId
      { layerId: 11, panelNum: 2, top: "77%", left: "61%" },
    ],
    // F: [
    //   { layerId: 12, panelNum: 1, top: "61%", left: "61%" },
    // ],
  },
 },
  // ────────────────────────────────────────────────
  //                CLX-3302
  // ────────────────────────────────────────────────
  "CLX-3302": {
    name: "CLX-3302",
    skeletonViews: {
      1: [
        { id: 1, img: "/C SK/15 GAF/V1/1.png" },
        { id: 2, img: "/C SK/15 GAF/V1/2.png" },
        { id: 3, img: "/C SK/15 GAF/V1/3.png" },
        { id: 4, img: "/C SK/15 GAF/V1/4.png" },
        { id: 5, img: "/C SK/15 GAF/V1/5.png" },
        { id: 6, img: "/C SK/15 GAF/V1/6.png" },
        { id: 7, img: "/C SK/15 GAF/V1/7.png" },
        { id: 8, img: "/C SK/15 GAF/V1/8.png" },
        { id: 9, img: "/C SK/15 GAF/V1/9.png" },
      ],
      2: [
        { id: 1, img: "/C SK/15 GAF/V2/1.png" },
        { id: 2, img: "/C SK/15 GAF/V2/2.png" },
        { id: 3, img: "/C SK/15 GAF/V2/3.png" },
        { id: 4, img: "/C SK/15 GAF/V2/4.png" },
        { id: 5, img: "/C SK/15 GAF/V2/5.png" },
        { id: 6, img: "/C SK/15 GAF/V2/6.png" },
        { id: 7, img: "/C SK/15 GAF/V2/7.png" },
        { id: 8, img: "/C SK/15 GAF/V2/8.png" },
        { id: 9, img: "/C SK/15 GAF/V2/9.png" },
        { id: 10, img: "/C SK/15 GAF/V2/10.png" },
        { id: 11, img: "/C SK/15 GAF/V2/11.png" },
      ],
      3: [
        { id: 1, img: "/C SK/15 GAF/V3/1.png" },
        { id: 2, img: "/C SK/15 GAF/V3/2.png" },
        { id: 3, img: "/C SK/15 GAF/V3/3.png" },
        { id: 4, img: "/C SK/15 GAF/V3/4.png" },
        { id: 5, img: "/C SK/15 GAF/V3/5.png" },
        { id: 6, img: "/C SK/15 GAF/V3/6.png" },
        { id: 7, img: "/C SK/15 GAF/V3/7.png" },
        { id: 8, img: "/C SK/15 GAF/V3/8.png" },
      ],
    },

    layerToPanelByView: {
      1: {
        1: { zone: "A", panelNum: 1 },
        2: { zone: "A", panelNum: 2 },
        3: { zone: "B", panelNum: 1 },
        4: { zone: "B", panelNum: 2 },
        5: { zone: "C", panelNum: 2 },
        6: { zone: "C", panelNum: 1 },
        7: { zone: "D", panelNum: 2 },

        // ... your current mapping
      },
      2: {
        1: { zone: "A", panelNum: 1 },
        2: { zone: "A", panelNum: 2 },
        3: { zone: "B", panelNum: 1 },
        4: { zone: "B", panelNum: 1 },
        5: { zone: "B", panelNum: 2 },
        6: { zone: "B", panelNum: 2 },
        7: { zone: "C", panelNum: 1 },
        8: { zone: "C", panelNum: 2 },
        9: { zone: "D", panelNum: 1 },
      },
      3: {
        1: { zone: "B", panelNum: 1 },
        2: { zone: "B", panelNum: 2 },
        3: { zone: "C", panelNum: 1 },
        4: { zone: "C", panelNum: 2 },
        5: { zone: "D", panelNum: 1 },
        6: { zone: "D", panelNum: 2 },
      },
    },

    // ── LEVELe-115 ──
    // Zones: A(2), B(3), C(2), D(2)
    // V1: A1→L1, A2→L2, B3→L3, B1→L4, C2→L5, C1→L6, D2→L7
    // V2: B2→L5(via B panelNum 2), D1→L9
    // Reconstructed: A(2), B(1,2,3), C(1,2), D(1,2)
    panelMap: {
      A: [
        { layerId: 1, panelNum: 1, top: "35%", left: "25%" },
        { layerId: 2, panelNum: 2, top: "40%", left: "50%" },
      ],
      B: [
        { layerId: 3, panelNum: 2, top: "55%", left: "80%" },
        { layerId: 5, panelNum: 1, top: "50%", left: "67%" },
      
      ],
      C: [
        { layerId: 8, panelNum: 1, top: "25%", left: "61%" },
        { layerId: 9, panelNum: 2, top: "77%", left: "61%" },
      ],
      D: [
        { layerId: 6, panelNum: 1, top: "25%", left: "61%" },
        { layerId: 7, panelNum: 2, top: "77%", left: "61%" },
      ],
    },
  },
};
